import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Sibling project with its own lint config + git history.
    "sap-odata-explorer/**",
    // Generated by postinstall - vendored pdfjs worker.
    "public/pdfjs-worker.mjs",
  ]),
]);

export default eslintConfig;
