import type { AgentId, Citation, Language } from "./types";
import { getAgent } from "./agents";
import { getBook } from "./kb";

interface ExplainInput {
  text: string;
  bookSlug?: string;
  paragraphId?: string;
  chapterTitle?: string;
  agentId: AgentId;
  language: Language;
}

interface ExplainOutput {
  text: string;
  citations: Citation[];
  source: "book" | "agent";
}

function extractTcodes(s: string): string[] {
  const out = new Set<string>();
  for (const m of s.matchAll(/\b([A-Z]{2,4}[0-9]{1,3}[A-Z]?)\b/g)) {
    if (m[1].length <= 6) out.add(m[1]);
  }
  return [...out].slice(0, 4);
}

function shortQuote(s: string, max = 220): string {
  const t = s.replace(/\s+/g, " ").trim();
  return t.length > max ? t.slice(0, max - 1) + "…" : t;
}

export function buildExplain({
  text,
  bookSlug,
  paragraphId,
  chapterTitle,
  agentId,
  language,
}: ExplainInput): ExplainOutput {
  const book = bookSlug ? getBook(bookSlug) : undefined;
  const agent = getAgent(agentId);
  const tcodes = extractTcodes(text);
  const copy = language === "he" ? agent.he : agent.en;
  const quote = shortQuote(text);
  const source: "book" | "agent" = book ? "book" : "agent";

  let body: string;
  if (language === "he") {
    body = [
      `**מה המשמעות**`,
      "",
      `הקטע שהדגשת מתוך **${book?.title ?? "ידע פנימי"}**${
        chapterTitle ? ` - פרק "${chapterTitle}"` : ""
      } מתאר רכיב מרכזי ב-${book?.module ?? "SAP S/4HANA"}.`,
      "",
      "> " + quote,
      "",
      `**צעדים לביצוע (לפי ${copy.name})**`,
      "",
      "1. ודא שהנתון העסקי מוגדר ב-SPRO תחת הסעיף המתאים למודול.",
      "2. הרץ את התהליך מול נתוני בדיקה ובדוק לוגים ב-SLG1.",
      "3. תעד את התוצאה בפורמט FS עם צילומי מסך.",
      "",
      tcodes.length
        ? `**טרנזקציות רלוונטיות:** ${tcodes.map((t) => "`" + t + "`").join(", ")}`
        : "",
      "",
      source === "book"
        ? `**מקור:** ${book?.title}${chapterTitle ? ` - ${chapterTitle}` : ""}.`
        : `**מקור:** הופק על ידי הסוכן **${copy.name}** על בסיס ידע עולמי - אין התאמה ישירה בספרים.`,
    ]
      .filter(Boolean)
      .join("\n");
  } else {
    body = [
      `**What this means**`,
      "",
      `The highlighted passage from **${book?.title ?? "internal knowledge"}**${
        chapterTitle ? ` - chapter "${chapterTitle}"` : ""
      } describes a core component of ${book?.module ?? "SAP S/4HANA"}.`,
      "",
      "> " + quote,
      "",
      `**Steps to apply (per ${copy.name})**`,
      "",
      "1. Make sure the business object is configured under the matching SPRO node.",
      "2. Execute against test data and review SLG1 application logs.",
      "3. Document the outcome in an FS with screenshots.",
      "",
      tcodes.length
        ? `**Relevant tcodes:** ${tcodes.map((t) => "`" + t + "`").join(", ")}`
        : "",
      "",
      source === "book"
        ? `**Source:** ${book?.title}${chapterTitle ? ` - ${chapterTitle}` : ""}.`
        : `**Source:** Generated by the **${copy.name}** agent from world knowledge - no direct passage in the indexed books.`,
    ]
      .filter(Boolean)
      .join("\n");
  }

  const citations: Citation[] = book
    ? [
        {
          bookSlug: book.slug,
          bookTitle: book.title,
          chapter: chapterTitle,
        },
      ]
    : [];

  // Reference paragraph id is encoded into the citation chapter when present
  // so the UI can deep-link back to the source row.
  if (citations[0] && paragraphId) {
    citations[0] = { ...citations[0], chapter: `${chapterTitle ?? "Source"} (${paragraphId.split("::p-").pop()})` };
  }

  return { text: body, citations, source };
}
