import type { Conversation } from "./types";
import { getAgent } from "./agents";

function isoLocal(ts: number) {
  return new Date(ts).toISOString();
}

export function conversationToMarkdown(conv: Conversation): string {
  const agent = getAgent(conv.agentId);
  const lines: string[] = [];
  lines.push(`# ${conv.title}`);
  lines.push("");
  lines.push(`> Agent: **${agent.en.name}** (${conv.agentId})`);
  lines.push(`> Created: ${isoLocal(conv.createdAt)}`);
  lines.push(`> Updated: ${isoLocal(conv.updatedAt)}`);
  lines.push("");

  for (const m of conv.messages) {
    if (m.role === "system") continue;
    const speaker = m.role === "user" ? "User" : agent.en.name;
    lines.push(`## ${speaker}`);
    lines.push("");
    lines.push(m.content || "_(empty)_");
    if (m.citations && m.citations.length > 0) {
      lines.push("");
      lines.push("**Sources:**");
      for (const c of m.citations) {
        const ch = c.chapter ? ` - ${c.chapter}` : "";
        const pg = c.page ? ` (p. ${c.page})` : "";
        lines.push(`- ${c.bookTitle}${ch}${pg}`);
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by SAP AI Knowledge Hub.");
  return lines.join("\n");
}

export function conversationToJson(conv: Conversation): string {
  return JSON.stringify(conv, null, 2);
}

export function safeFilename(name: string, ext: string): string {
  const base = name
    .replace(/[\s ]+/g, "-")
    .replace(/[^A-Za-z0-9_\-֐-׿]/g, "")
    .slice(0, 60) || "conversation";
  return `${base}.${ext}`;
}

export function triggerDownload(filename: string, mime: string, body: string) {
  if (typeof window === "undefined") return;
  const blob = new Blob([body], { type: mime + ";charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
