# -*- coding: utf-8 -*-
"""
SAP PP-PI (Production Planning for Process Industries) migration data model - Project NEO / CBC.
Single source for both the .xlsx builder and the web portal.

Field tuple: (tech, english, hebrew, data_type, length, key)   key in {PK, FK, PK/FK, -}
Table dict : name, he, en, tcodes, join (SQL/CDS JOIN ON), guide (Hebrew functional), s4 (gap note),
             help (url,label), fields[...]
Verify version-sensitive metadata (lengths, S/4 simplification) in SE11 / SAP Help Portal.
"""

H = "https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE"
FIORI = "https://fioriappslibrary.hana.ondemand.com/"
SIC = "https://launchpad.support.sap.com/#/sic"
def NOTE(n): return f"https://launchpad.support.sap.com/#/notes/{n}"

TOPICS = [
# ===================== 1. MATERIAL MASTER & UoM ============================
{"title": "1. נתוני אב חומר ויחידות מידה (Material & UoM)", "theme": "master", "tables": [
 {"name": "MARA", "he": "נתוני אב חומר כלליים", "en": "General material data",
  "tcodes": "MM01/MM02/MM03; MM50, MMSC", "join": "(header - root of material model)",
  "guide": "טבלת הליבה של כל חומר ב-CBC (חומרי גלם, תרכיזים, חומרי אריזה, מוצרים מוגמרים). מפתח MATNR מורחב מ-18 ל-40 תווים ב-S/4HANA - קריטי לממשקי IDoc ל-Zetes/Daymax ולברקודים. כל פעולת ייצור (COR1/COR2) נשענת על רשומת חומר תקינה.",
  "s4": "MATNR מורחב 18->40 (SAP Note 2267140); בדוק ממשקים, ברקודים והמרות EAN.",
  "help": (H, "SAP Help - Material Master"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK"),
             ("MTART","Material type","סוג חומר","CHAR","4","FK"),
             ("MEINS","Base unit of measure","יחידת מידה בסיסית","UNIT","3","FK"),
             ("MATKL","Material group","קבוצת חומר","CHAR","9","FK"),
             ("GROES","Size / dimensions","גודל / מידות","CHAR","32","-"),
             ("BRGEW","Gross weight","משקל ברוטו","QUAN","13","-"),
             ("NTGEW","Net weight","משקל נטו","QUAN","13","-"),
             ("XCHPF","Batch management indicator","ניהול אצוות","CHAR","1","-")]},
 {"name": "MAKT", "he": "תיאורי חומר (טקסטים)", "en": "Material descriptions",
  "tcodes": "MM01/MM02/MM03", "join": "FROM MAKT JOIN MARA ON MAKT.MATNR = MARA.MATNR",
  "guide": "תיאורי החומר הרב-לשוניים (עברית/אנגלית) המוצגים בפק\"ע, בתעודות ובממשקי הלוגיסטיקה. חיוני לתצוגה דו-לשונית במסופי Zetes.",
  "s4": "ללא שינוי; MATNR מורחב משפיע על המפתח.",
  "help": (H, "SAP Help - Material Master"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("SPRAS","Language key","שפה","LANG","1","PK"),
             ("MAKTX","Material description","תיאור חומר","CHAR","40","-"),
             ("MAKTG","Description (upper case)","תיאור (אותיות גדולות)","CHAR","40","-")]},
 {"name": "MARC", "he": "נתוני חומר ברמת מפעל", "en": "Plant data for material",
  "tcodes": "MM01/MM02; MD04, CO09", "join": "FROM MARC JOIN MARA ON MARC.MATNR = MARA.MATNR",
  "guide": "פרמטרי התכנון והייצור של החומר במפעל CBC הספציפי: סוג רכש, MRP, אופק תכנון, גרסת ייצור ברירת מחדל. שדה SBDKZ/SFCPF שולט בזרימת הייצור (Process Order).",
  "s4": "MRP Live מחליף MRP קלאסי; שדות תכנון נשמרים אך הביצוע ב-MATDOC/ACDOCA.",
  "help": (H, "SAP Help - Plant Data"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK"),
             ("DISPO","MRP controller","אחראי MRP","CHAR","3","FK"),
             ("DISMM","MRP type","סוג MRP","CHAR","2","-"),
             ("BESKZ","Procurement type","סוג רכש","CHAR","1","-"),
             ("SOBSL","Special procurement","רכש מיוחד","CHAR","2","-"),
             ("FEVOR","Production scheduler","מתזמן ייצור","CHAR","3","FK"),
             ("SERNP","Serial number profile","פרופיל מספר סידורי","CHAR","4","-")]},
 {"name": "MARD", "he": "נתוני חומר ברמת מחסן/מלאי", "en": "Storage location / stock data",
  "tcodes": "MMBE; MB52", "join": "FROM MARD JOIN MARC ON MARD.MATNR = MARC.MATNR AND MARD.WERKS = MARC.WERKS",
  "guide": "מלאי החומר לפי מחסן במפעל. בסיס לפליטת חומרי גלם לפק\"ע ולקליטת מוצר מוגמר; מסונכרן עם מסופי Zetes/Daymax בזמן אמת.",
  "s4": "מלאי מנוהל ב-MATDOC; MARD הופך ל-Aggregate/View.",
  "help": (H, "SAP Help - Inventory"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK/FK"),
             ("LGORT","Storage location","מחסן","CHAR","4","PK"),
             ("LABST","Unrestricted stock","מלאי פנוי","QUAN","13","-"),
             ("INSME","Stock in quality inspection","מלאי בבדיקת איכות","QUAN","13","-")]},
 {"name": "MARM", "he": "המרות יחידות מידה חלופיות", "en": "Units of measure conversions",
  "tcodes": "MM02 (תצוגת UoM)", "join": "FROM MARM JOIN MARA ON MARM.MATNR = MARA.MATNR",
  "guide": "מקדמי המרה בין יחידות (UMREZ מונה / UMREN מכנה) - לדוגמה ארגז=24 בקבוקים, משטח=ארגזים. קריטי לבקרת פחת ייצור של 1%: עיגול שגוי במקדם גורם לסטיית מלאי. EAN11 לברקוד.",
  "s4": "ללא שינוי מבני; אמת מקדמי עיגול (rounding) למניעת סטיות מלאי.",
  "help": (H, "SAP Help - Units of Measure"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("MEINH","Alternative unit of measure","יחידת מידה חלופית","UNIT","3","PK"),
             ("UMREZ","Numerator for conversion","מונה להמרה","DEC","5","-"),
             ("UMREN","Denominator for conversion","מכנה להמרה","DEC","5","-"),
             ("EAN11","International article number (EAN/UPC)","ברקוד בינלאומי","CHAR","18","-"),
             ("MESUB","Lowest level UoM","יחידה ברמה הנמוכה","UNIT","3","-")]},
 {"name": "MEAN", "he": "ברקודים / EAN לחומר", "en": "International article numbers (EANs)",
  "tcodes": "MM02", "join": "FROM MEAN JOIN MARA ON MEAN.MATNR = MARA.MATNR",
  "guide": "ניהול ברקודים מרובים לחומר (EAN13, UPC, GTIN) לפי יחידת מידה. מקור הסריקה במסופי Zetes בקליטה ובמשלוח.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - EAN"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("MEINH","Unit of measure","יחידת מידה","UNIT","3","PK"),
             ("EAN11","EAN / barcode","ברקוד EAN","CHAR","18","PK"),
             ("EANTP","EAN category","סוג EAN","CHAR","2","-"),
             ("HPEAN","Main EAN indicator","ברקוד ראשי","CHAR","1","-")]},
 {"name": "MBEW", "he": "הערכת חומר (Valuation)", "en": "Material valuation",
  "tcodes": "MM02; MR21, CKM3", "join": "FROM MBEW JOIN MARA ON MBEW.MATNR = MARA.MATNR",
  "guide": "מחיר התקן/ממוצע נע של החומר לתמחיר ייצור והתחשבנות פק\"ע. ב-CBC משמש לחישוב עלות תרכיז/מוצר מוגמר.",
  "s4": "Material Ledger חובה ב-S/4HANA; הערכה ב-ACDOCA/ACDOCC.",
  "help": (NOTE(2267835), "SAP Note - Material Ledger"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("BWKEY","Valuation area","אזור הערכה","CHAR","4","PK"),
             ("BWTAR","Valuation type","סוג הערכה","CHAR","10","PK"),
             ("VPRSV","Price control (S/V)","בקרת מחיר","CHAR","1","-"),
             ("STPRS","Standard price","מחיר תקן","CURR","11","-"),
             ("PEINH","Price unit","יחידת מחיר","DEC","5","-")]},
 {"name": "MVKE", "he": "נתוני חומר ברמת מכירות", "en": "Sales data for material",
  "tcodes": "MM01/MM02", "join": "FROM MVKE JOIN MARA ON MVKE.MATNR = MARA.MATNR",
  "guide": "נתוני מכירה של מוצר מוגמר (ארגון מכירות, ערוץ הפצה) - מחבר את הייצור לשרשרת ההפצה של CBC.",
  "s4": "ללא שינוי; לקוחות דרך Business Partner.",
  "help": (H, "SAP Help - Sales Data"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("VKORG","Sales organization","ארגון מכירות","CHAR","4","PK"),
             ("VTWEG","Distribution channel","ערוץ הפצה","CHAR","2","PK"),
             ("MTPOS","Item category group","קבוצת קטגוריית פריט","CHAR","4","-")]},
 {"name": "MLAN", "he": "נתוני מס לחומר (לפי מדינה)", "en": "Material tax data",
  "tcodes": "MM01/MM02", "join": "FROM MLAN JOIN MARA ON MLAN.MATNR = MARA.MATNR",
  "guide": "סיווג מס (מע\"מ/בלו) לחומר לפי מדינה - רלוונטי למשקאות החייבים בבלו/מס בריאות בישראל.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Tax Classification"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("ALAND","Departure country","מדינת מקור","CHAR","3","PK"),
             ("TAXM1","Tax classification","סיווג מס","CHAR","1","-")]},
 {"name": "MLGN", "he": "נתוני חומר ברמת מחסן (WM)", "en": "Material data for warehouse number",
  "tcodes": "MM01/MM02", "join": "FROM MLGN JOIN MARA ON MLGN.MATNR = MARA.MATNR",
  "guide": "פרמטרי ניהול מחסן (WM/EWM) של החומר - יחידת בסיס לאחסון, אסטרטגיית העלאה/הורדה. ממשק למסופי Zetes.",
  "s4": "EWM אסטרטגי; LE-WM קלאסי נתמך עם הגבלות.",
  "help": (H, "SAP Help - Warehouse"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("LGNUM","Warehouse number","מספר מחסן","CHAR","3","PK"),
             ("LTKZA","Stock removal strategy","אסטרטגיית הורדה","CHAR","3","-"),
             ("LTKZE","Stock placement strategy","אסטרטגיית העלאה","CHAR","3","-")]},
 {"name": "MLGT", "he": "נתוני חומר לפי טיפוס אחסון", "en": "Material data for storage type",
  "tcodes": "MM01/MM02", "join": "FROM MLGT JOIN MLGN ON MLGT.MATNR = MLGN.MATNR AND MLGT.LGNUM = MLGN.LGNUM",
  "guide": "כמויות/אזורי אחסון לפי טיפוס במחסן - בקרת מיקום אצווה במחסן הקירור/יבש.",
  "s4": "EWM אסטרטגי.",
  "help": (H, "SAP Help - Storage Type"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("LGNUM","Warehouse number","מספר מחסן","CHAR","3","PK/FK"),
             ("LGTYP","Storage type","טיפוס אחסון","CHAR","3","PK"),
             ("LPMAX","Maximum bin quantity","כמות תא מקסימלית","QUAN","13","-")]},
 {"name": "MDMA", "he": "אזורי MRP לחומר", "en": "MRP areas for material",
  "tcodes": "MM02; MDLV", "join": "FROM MDMA JOIN MARC ON MDMA.MATNR = MARC.MATNR AND MDMA.WERKS = MARC.WERKS",
  "guide": "הפרדת תכנון לאזורי MRP (קו ייצור/מחסן) בתוך המפעל - מאפשר תכנון נפרד לקו בקבוק מול קו פחית.",
  "s4": "אזורי MRP פעילים כברירת מחדל ב-MRP Live.",
  "help": (H, "SAP Help - MRP Areas"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK/FK"),
             ("BERID","MRP area","אזור MRP","CHAR","10","PK"),
             ("DISMM","MRP type","סוג MRP","CHAR","2","-")]},
 {"name": "QMAT", "he": "הגדרות בדיקת איכות לחומר", "en": "Inspection setup data for material",
  "tcodes": "QA08; MM02", "join": "FROM QMAT JOIN MARC ON QMAT.MATNR = MARC.MATNR AND QMAT.WERKS = MARC.WERKS",
  "guide": "הפעלת סוגי בדיקה (קליטה/ייצור/שחרור) לחומר - מחבר את הייצור ל-QM. קריטי לשחרור אצווה לפני משלוח.",
  "s4": "ללא שינוי מבני.",
  "help": (H, "SAP Help - Quality Inspection"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK/FK"),
             ("ART","Inspection type","סוג בדיקה","CHAR","8","PK"),
             ("AKTIV","Active indicator","פעיל","CHAR","1","-")]},
 {"name": "MCH1", "he": "אצוות חומר (Batches)", "en": "Batch master records",
  "tcodes": "MSC1N/MSC2N/MSC3N", "join": "FROM MCH1 JOIN MARA ON MCH1.MATNR = MARA.MATNR",
  "guide": "רשומות האצווה של החומר - קריטי במשקאות לניהול תאריך תפוגה (VFDAT/BBD), תאריך ייצור ומעקב גנאלוגיה (Track & Trace). כל פליטה/קליטה בקו מנוהלת לפי אצווה ומסונכרנת עם Zetes.",
  "s4": "ללא שינוי מבני; MATNR מורחב 18->40 במפתח.",
  "help": (H, "SAP Help - Batch Management"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("CHARG","Batch number","מספר אצווה","CHAR","10","PK"),
             ("ERSDA","Creation date","תאריך יצירה","DATS","8","-"),
             ("VFDAT","Shelf life expiration / BBD","תאריך תפוגה","DATS","8","-"),
             ("HSDAT","Date of manufacture","תאריך ייצור","DATS","8","-"),
             ("LICHA","Vendor batch","אצוות ספק","CHAR","15","-"),
             ("ZUSTD","Batch status (released/restricted)","סטטוס אצווה","CHAR","1","-")]},
 {"name": "MCHA", "he": "אצוות חומר ברמת מפעל", "en": "Batch master at plant level",
  "tcodes": "MSC2N", "join": "FROM MCHA JOIN MCH1 ON MCHA.MATNR = MCH1.MATNR AND MCHA.CHARG = MCH1.CHARG",
  "guide": "נתוני האצווה הספציפיים למפעל (סטטוס שחרור, מאפייני סיווג). מאפשר שחרור/חסימת אצווה לפי תוצאות בדיקת איכות לפני משלוח.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Batch at Plant"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK"),
             ("CHARG","Batch number","מספר אצווה","CHAR","10","PK/FK"),
             ("ZUSCH","Batch status key","מפתח סטטוס אצווה","CHAR","2","-")]},
 {"name": "T006", "he": "יחידות מידה (Customizing)", "en": "Units of measure",
  "tcodes": "CUNI; SPRO", "join": "FROM MARM JOIN T006 ON MARM.MEINH = T006.MSEHI",
  "guide": "הגדרת יחידות המידה הגלובליות (מימד, מקדם ISO). בסיס לכל המרות ה-UoM ולעיגול בבקרת פחת.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - CUNI"),
  "fields": [("MSEHI","Unit of measure","יחידת מידה","UNIT","3","PK"),
             ("DIMID","Dimension key","מפתח מימד","CHAR","6","FK"),
             ("ZAEHL","Numerator (ISO)","מונה ISO","DEC","5","-"),
             ("NENNR","Denominator (ISO)","מכנה ISO","DEC","5","-"),
             ("DECAN","Decimal places for rounding","ספרות עשרוניות","NUMC","1","-")]},
]},
# ===================== 2. BILL OF MATERIALS ================================
{"title": "2. עץ מוצר (BOM)", "theme": "master", "tables": [
 {"name": "MAST", "he": "קישור חומר לעץ מוצר", "en": "Material to BOM link",
  "tcodes": "CS01/CS02/CS03", "join": "FROM MAST JOIN MARA ON MAST.MATNR = MARA.MATNR",
  "guide": "מקשר בין חומר/מפעל לבין עץ המוצר (Recipe BOM). מפתח ההצטרפות לכל פיצוץ רכיבים בפק\"ע. עץ מוצר = 'עץ מוצר' / Bill of Material.",
  "s4": "ללא שינוי; MATNR מורחב משפיע על המפתח ועל IDNRK.",
  "help": (H, "SAP Help - Bill of Material"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK"),
             ("STLAN","BOM usage (1=Production)","שימוש עץ מוצר","CHAR","1","PK"),
             ("STLNR","Bill of material number","מספר עץ מוצר","CHAR","8","FK"),
             ("STLAL","Alternative BOM","חלופת עץ מוצר","CHAR","2","PK")]},
 {"name": "STKO", "he": "כותרת עץ מוצר", "en": "BOM header",
  "tcodes": "CS01/CS02/CS03", "join": "FROM STKO JOIN MAST ON STKO.STLNR = MAST.STLNR",
  "guide": "כותרת עץ המוצר: כמות בסיס, יחידה, סטטוס ותוקף. כמות הבסיס (BMENG) קובעת את יחס הרכיבים - קריטי לדיוק מתכון/פחת.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - BOM Header"),
  "fields": [("STLTY","BOM category","קטגוריית עץ מוצר","CHAR","1","PK"),
             ("STLNR","Bill of material number","מספר עץ מוצר","CHAR","8","PK"),
             ("STLAL","Alternative BOM","חלופת עץ מוצר","CHAR","2","PK"),
             ("BMENG","Base quantity","כמות בסיס","QUAN","13","-"),
             ("BMEIN","Base unit of measure","יחידת בסיס","UNIT","3","FK"),
             ("STLST","BOM status","סטטוס עץ מוצר","NUMC","2","-")]},
 {"name": "STPO", "he": "פריטי עץ מוצר (רכיבים)", "en": "BOM item",
  "tcodes": "CS02; CS11, CS15", "join": "FROM STPO JOIN STKO ON STPO.STLNR = STKO.STLNR AND STPO.STLTY = STKO.STLTY",
  "guide": "רכיבי עץ המוצר: כל חומר גלם/אריזה, כמותו (MENGE) וסוג הפריט. כאן מוגדר פחת רכיב (AUSCH %) לבקרת 1% פחת ייצור.",
  "s4": "ללא שינוי; IDNRK מורחב 18->40.",
  "help": (H, "SAP Help - BOM Item"),
  "fields": [("STLTY","BOM category","קטגוריית עץ מוצר","CHAR","1","PK/FK"),
             ("STLNR","Bill of material number","מספר עץ מוצר","CHAR","8","PK/FK"),
             ("STLKN","BOM item node number","מספר צומת פריט","NUMC","8","PK"),
             ("POSNR","BOM item number","מספר פריט","CHAR","4","-"),
             ("IDNRK","Component (BOM item material)","רכיב / חומר","CHAR","18->40","FK"),
             ("MENGE","Component quantity","כמות רכיב","QUAN","13","-"),
             ("MEINS","Component unit","יחידת רכיב","UNIT","3","FK"),
             ("AUSCH","Component scrap (%)","פחת רכיב (%)","DEC","6","-"),
             ("POSTP","Item category","סוג פריט","CHAR","1","-")]},
 {"name": "STAS", "he": "בחירת פריטי עץ מוצר", "en": "BOM item selection",
  "tcodes": "CS02 (CC)", "join": "FROM STAS JOIN STKO ON STAS.STLNR = STKO.STLNR",
  "guide": "מקשר בין פריטי STPO לחלופה/שינוי ההנדסי (ECM). שולט אילו רכיבים תקפים לתאריך נתון.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - BOM Variants"),
  "fields": [("STLTY","BOM category","קטגוריית עץ מוצר","CHAR","1","PK/FK"),
             ("STLNR","Bill of material number","מספר עץ מוצר","CHAR","8","PK/FK"),
             ("STLAL","Alternative BOM","חלופה","CHAR","2","PK"),
             ("STLKN","Item node number","מספר צומת","NUMC","8","FK"),
             ("STASZ","Internal counter","מונה פנימי","NUMC","8","PK")]},
 {"name": "STZU", "he": "טבלת היסטוריה/קישור לעץ מוצר", "en": "BOM history / link table",
  "tcodes": "CS80 (CC overview)", "join": "FROM STZU JOIN STKO ON STZU.STLNR = STKO.STLNR",
  "guide": "מנהל את היסטוריית השינויים וקישורי ה-ECM של עץ המוצר - חיוני למעקב גרסאות מתכון לאורך זמן.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Engineering Change"),
  "fields": [("STLTY","BOM category","קטגוריית עץ מוצר","CHAR","1","PK/FK"),
             ("STLNR","Bill of material number","מספר עץ מוצר","CHAR","8","PK/FK"),
             ("STLAN","BOM usage","שימוש","CHAR","1","-"),
             ("AENNR","Change number (ECM)","מספר שינוי הנדסי","CHAR","12","FK")]},
 {"name": "STPU", "he": "טקסטים ארוכים לפריט עץ מוצר", "en": "BOM sub-items / texts",
  "tcodes": "CS02", "join": "FROM STPU JOIN STPO ON STPU.STLKN = STPO.STLKN",
  "guide": "תת-פריטים/כמויות נקודתיות של רכיב בעץ המוצר (לדוגמה כמות לפי מיקום התקנה).",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - BOM Sub-items"),
  "fields": [("STLKN","Item node number","מספר צומת פריט","NUMC","8","PK/FK"),
             ("SUMNR","Sub-item number","מספר תת-פריט","NUMC","4","PK"),
             ("MENGE","Sub-item quantity","כמות תת-פריט","QUAN","13","-")]},
 {"name": "KDST", "he": "שימוש עץ מוצר בהזמנת לקוח", "en": "BOM explosion (sales order)",
  "tcodes": "CS61", "join": "FROM KDST JOIN MAST ON KDST.MATNR = MAST.MATNR",
  "guide": "מקשר עצי מוצר ספציפיים להזמנת לקוח (Make-to-Order) - רלוונטי לייצור מבצעים/מותגים פרטיים.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Sales Order BOM"),
  "fields": [("VBELN","Sales document","מסמך מכירה","CHAR","10","PK"),
             ("POSNR","Sales document item","פריט מסמך מכירה","NUMC","6","PK"),
             ("MATNR","Material number","מספר חומר","CHAR","18->40","FK"),
             ("STLNR","BOM number","מספר עץ מוצר","CHAR","8","FK")]},
]},
# ===================== 3. MASTER RECIPE & OPERATIONS =======================
{"title": "3. מתכון ייצור ופעולות (Master Recipe)", "theme": "trans", "tables": [
 {"name": "PLKO", "he": "כותרת מתכון ייצור / רשימת פעולות", "en": "Task list / recipe header",
  "tcodes": "C201/C202/C203", "join": "FROM PLKO JOIN MAPL ON PLKO.PLNTY = MAPL.PLNTY AND PLKO.PLNNR = MAPL.PLNNR",
  "guide": "כותרת מתכון הייצור (Master Recipe, PLNTY='2'). מגדיר אצווה תקנית, סטטוס ושימוש. 'מתכון ייצור' = Master Recipe. ב-CBC כל משקה מיוצר לפי מתכון מאושר.",
  "s4": "ללא שינוי מבני; Fiori 'Manage Master Recipes'.",
  "help": (H, "SAP Help - Master Recipe"),
  "fields": [("PLNTY","Task list type (2=recipe)","סוג רשימה","CHAR","1","PK"),
             ("PLNNR","Key for task list group","קבוצת רשימת פעולות","CHAR","8","PK"),
             ("PLNAL","Group counter","מונה קבוצה / חלופה","CHAR","2","PK"),
             ("VERWE","Task list usage","שימוש","CHAR","3","FK"),
             ("STATU","Task list status","סטטוס","CHAR","2","-"),
             ("LOSVN","Lot size from","גודל אצווה מ","QUAN","13","-"),
             ("LOSBS","Lot size to","גודל אצווה עד","QUAN","13","-")]},
 {"name": "PLPO", "he": "פעולות/פאזות במתכון", "en": "Task list - operation / activity",
  "tcodes": "C202", "join": "FROM PLPO JOIN PLAS ON PLPO.PLNTY = PLAS.PLNTY AND PLPO.PLNNR = PLAS.PLNNR AND PLPO.PLNKN = PLAS.PLNKN",
  "guide": "פעולות ופאזות הייצור (ערבוב, פסטור, מילוי). מפתח בקרה (STEUS) קובע אם הפעולה פנימית/קבלן, ומפעיל הוראות תהליך (Process Instructions) ל-PI sheet ולבקרים. ARBPL=משאב.",
  "s4": "ללא שינוי; ביצוע דרך Control Recipe / PI sheet.",
  "help": (H, "SAP Help - Recipe Operations"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("PLNKN","Node number (operation)","מספר צומת פעולה","NUMC","8","PK"),
             ("VORNR","Operation number","מספר פעולה","CHAR","4","-"),
             ("ARBID","Work center / resource (object id)","משאב (מזהה אובייקט)","NUMC","8","FK"),
             ("STEUS","Control key","מפתח בקרה","CHAR","4","FK"),
             ("LTXA1","Operation short text","תיאור פעולה","CHAR","40","-"),
             ("VGW01","Standard value 1 (setup)","ערך תקן 1 (הקמה)","QUAN","9","-"),
             ("VGW02","Standard value 2 (machine)","ערך תקן 2 (מכונה)","QUAN","9","-")]},
 {"name": "PLAS", "he": "שיוך/בחירת פעולות לרשימה", "en": "Task list - operation selection",
  "tcodes": "C202", "join": "FROM PLAS JOIN PLKO ON PLAS.PLNTY = PLKO.PLNTY AND PLAS.PLNNR = PLKO.PLNNR",
  "guide": "מקשר פעולות (PLPO) לכותרת ולרצף, ושולט בתוקף לפי שינוי הנדסי. שכבת הבחירה של הפעולות התקפות.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Operation Selection"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("PLNAL","Group counter","מונה קבוצה","CHAR","2","PK"),
             ("PLNKN","Node number","מספר צומת","NUMC","8","PK"),
             ("ZAEHL","Internal counter","מונה פנימי","NUMC","8","PK"),
             ("LOEKZ","Deletion indicator","מחוון מחיקה","CHAR","1","-")]},
 {"name": "PLFL", "he": "רצפים במתכון", "en": "Task list - sequences",
  "tcodes": "C202", "join": "FROM PLFL JOIN PLKO ON PLFL.PLNNR = PLKO.PLNNR",
  "guide": "מגדיר רצפי פעולות (סטנדרטי/מקביל/חלופי) - מאפשר ייצור מקבילי בקווי בקבוק/פחית.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Sequences"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("PLNFL","Sequence number","מספר רצף","CHAR","6","PK"),
             ("FLGAT","Sequence category","קטגוריית רצף","CHAR","1","-")]},
 {"name": "PLMZ", "he": "שיוך רכיבים לפעולות", "en": "Component allocation (BOM to operation)",
  "tcodes": "C202 (Comp. Alloc.)", "join": "FROM PLMZ JOIN PLPO ON PLMZ.PLNKN = PLPO.PLNKN",
  "guide": "מקשר רכיבי עץ מוצר (STPO) לפעולות במתכון - קובע באיזו פאזה נצרך כל חומר גלם. בסיס לפליטת חומרים מדורגת בפק\"ע.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Component Allocation"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("ZUONR","Allocation node","צומת שיוך","NUMC","8","PK"),
             ("PLNKN","Operation node","צומת פעולה","NUMC","8","FK"),
             ("STLKN","BOM item node","צומת פריט עץ מוצר","NUMC","8","FK")]},
 {"name": "PLMK", "he": "מאפייני בדיקה במתכון", "en": "Inspection characteristics",
  "tcodes": "C202; QP01", "join": "FROM PLMK JOIN PLPO ON PLMK.PLNKN = PLPO.PLNKN",
  "guide": "מאפייני בדיקת איכות המשובצים בפעולות המתכון (Brix, pH, CO2, טמפ'). מפעיל מסמכי בדיקה אוטומטיים בפק\"ע - לב בקרת האיכות של CBC.",
  "s4": "ללא שינוי מבני.",
  "help": (H, "SAP Help - Inspection Characteristics"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("MERKNR","Inspection characteristic number","מספר מאפיין בדיקה","NUMC","4","PK"),
             ("PLNKN","Operation node","צומת פעולה","NUMC","8","FK"),
             ("VERWMERKM","Master inspection characteristic","מאפיין בדיקה ראשי","CHAR","8","FK"),
             ("SOLLWERT","Target value","ערך יעד","CHAR","18","-")]},
 {"name": "MAPL", "he": "שיוך חומר למתכון/רשימת פעולות", "en": "Material to task list assignment",
  "tcodes": "C201/C202", "join": "FROM MAPL JOIN MARC ON MAPL.MATNR = MARC.MATNR AND MAPL.WERKS = MARC.WERKS",
  "guide": "מקשר בין חומר (מוצר) למתכון הייצור שלו במפעל. נקודת ההצטרפות שגרסת הייצור (MKAL) מצביעה אליה.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Material Assignment"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK"),
             ("PLNTY","Task list type","סוג רשימה","CHAR","1","FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","FK"),
             ("PLNAL","Group counter","מונה קבוצה","CHAR","2","FK")]},
 {"name": "FHMI", "he": "שיוך כלי עזר ייצור (PRT) לפעולה", "en": "Production resources/tools allocation",
  "tcodes": "C202 (PRT)", "join": "FROM FHMI JOIN PLPO ON FHMI.PLNKN = PLPO.PLNKN",
  "guide": "מקשר כלי עזר ייצור (תבניות, מסננים, פורמטים) לפעולות המתכון - מעקב כיול וזמינות PRT.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - PRT"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("PLNKN","Operation node","צומת פעולה","NUMC","8","FK"),
             ("FHMNR","PRT (resource/tool)","כלי עזר ייצור","CHAR","18","FK")]},
 {"name": "PLZU", "he": "קישור היסטוריית רשימת פעולות", "en": "Task list link / history",
  "tcodes": "C202", "join": "FROM PLZU JOIN PLKO ON PLZU.PLNNR = PLKO.PLNNR",
  "guide": "מנהל גרסאות ושינויים הנדסיים של רשימת הפעולות/המתכון - מעקב אחר עדכוני מתכון מאושרים.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Task List Change"),
  "fields": [("PLNTY","Task list type","סוג רשימה","CHAR","1","PK/FK"),
             ("PLNNR","Task list group","קבוצת רשימה","CHAR","8","PK/FK"),
             ("AENNR","Change number","מספר שינוי","CHAR","12","FK")]},
 {"name": "TC60", "he": "מאפייני הוראות תהליך (PI)", "en": "Process instruction characteristics",
  "tcodes": "O09C; SPRO", "join": "FROM PLPO JOIN TC60 ON PLPO.STEUS = TC60.STEUS",
  "guide": "מגדיר את מאפייני הוראות התהליך (Process Instructions) שנשלחים לבקר/PI sheet בעת שחרור פק\"ע - לב ה-PP-PI מול אוטומציית הקו.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Process Instructions"),
  "fields": [("STEUS","Control key","מפתח בקרה","CHAR","4","PK"),
             ("PVZNR","PI characteristic number","מספר מאפיין PI","NUMC","4","PK"),
             ("ATNAM","Characteristic name","שם מאפיין","CHAR","30","FK")]},
 {"name": "TCA01", "he": "פרופיל רשימת פעולות (Customizing)", "en": "Task list profile",
  "tcodes": "SPRO", "join": "FROM PLKO JOIN TCA01 ON PLKO.PROFIDNETZ = TCA01.PROFIDNETZ",
  "guide": "פרופיל ברירת מחדל לרשימות פעולות/מתכונים (ערכי ברירת מחדל למפתחות בקרה, יחידות). מאיץ תחזוקת מתכונים אחידה.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Task List Profile"),
  "fields": [("PROFIDNETZ","Profile ID","מזהה פרופיל","CHAR","7","PK"),
             ("PLNTY","Task list type","סוג רשימה","CHAR","1","FK"),
             ("STEUS","Default control key","מפתח בקרה ברירת מחדל","CHAR","4","FK")]},
]},
# ===================== 4. PRODUCTION VERSIONS ==============================
{"title": "4. גרסאות ייצור (Production Versions - חובה ב-S/4)", "theme": "cross", "tables": [
 {"name": "MKAL", "he": "גרסאות ייצור לחומר", "en": "Production versions for materials",
  "tcodes": "C223; MM02 (PV)", "join": "FROM MKAL JOIN MARC ON MKAL.MATNR = MARC.MATNR AND MKAL.WERKS = MARC.WERKS",
  "guide": "'גרסת ייצור' (Production Version) מקשרת חומר -> עץ מוצר (STLAL) + מתכון (PLNNR) + קו ייצור. ב-S/4HANA היא חובה מוחלטת (100%) לכל ביצוע ייצור - מחליפה את לוגיקת בחירת BOM/Routing האוטומטית של ECC. ב-CBC כל שילוב מוצר/קו = גרסה. ללא PV תקפה הפק\"ע (COR1) לא תיווצר.",
  "s4": "חובה 100% ב-S/4HANA - הרץ C223 ובדוק תוקף/עקביות לכל חומר מיוצר לפני ההמרה (Pre-check קריטי).",
  "help": (NOTE(2655896), "SAP Note - Production Versions Mandatory"),
  "fields": [("MATNR","Material number","מספר חומר","CHAR","18->40","PK/FK"),
             ("WERKS","Plant","מפעל","CHAR","4","PK/FK"),
             ("VERID","Production version","מזהה גרסת ייצור","CHAR","4","PK"),
             ("TEXT1","Production version text","תיאור גרסת ייצור","CHAR","40","-"),
             ("ADATU","Valid-from date","תקף מ","DATS","8","-"),
             ("BDATU","Valid-to date","תקף עד","DATS","8","-"),
             ("BSTMI","Lot size from","גודל אצווה מ","QUAN","13","-"),
             ("BSTMA","Lot size to","גודל אצווה עד","QUAN","13","-"),
             ("STLAL","Alternative BOM","חלופת עץ מוצר","CHAR","2","FK"),
             ("STLAN","BOM usage","שימוש עץ מוצר","CHAR","1","FK"),
             ("PLNTY","Task list type (recipe)","סוג רשימה","CHAR","1","FK"),
             ("PLNNR","Task list group (recipe)","קבוצת מתכון","CHAR","8","FK"),
             ("ALNAL","Task list group counter","מונה רשימה","CHAR","2","FK"),
             ("MDV01","Production line / resource","קו ייצור / משאב","CHAR","8","FK"),
             ("PRFG_NEW","Detailed PV check status","סטטוס בדיקת תקינות","CHAR","1","-")]},
]},
# ===================== 5. RESOURCES / WORK CENTERS =========================
{"title": "5. משאבים / מרכזי עבודה (Resources)", "theme": "master", "tables": [
 {"name": "CRHD", "he": "כותרת משאב / מרכז עבודה", "en": "Work center / resource header",
  "tcodes": "CRC1/CRC2/CRC3; CR01", "join": "(header - root of resource model)",
  "guide": "המשאב (קו מילוי, ערבל, פסטרייזר) שעליו מתבצעות פעולות המתכון. OBJTY='A'. מקושר לקיבולת ולמרכז עלות. ב-CBC כל קו ייצור = משאב עם קיבולת מתוזמנת.",
  "s4": "ללא שינוי מבני; Fiori 'Manage Work Centers'.",
  "help": (H, "SAP Help - Work Center"),
  "fields": [("OBJTY","Object type (A=work center)","סוג אובייקט","CHAR","2","PK"),
             ("OBJID","Object ID","מזהה אובייקט","NUMC","8","PK"),
             ("ARBPL","Work center / resource code","קוד משאב","CHAR","8","-"),
             ("WERKS","Plant","מפעל","CHAR","4","FK"),
             ("VERWE","Usage","שימוש","CHAR","4","FK"),
             ("VERAN","Person responsible","אחראי","CHAR","3","-"),
             ("PLANV","Capacity planner group","קבוצת מתכנן קיבולת","CHAR","3","-")]},
 {"name": "CRTX", "he": "טקסטים של משאב", "en": "Work center / resource texts",
  "tcodes": "CRC2/CRC3", "join": "FROM CRTX JOIN CRHD ON CRTX.OBJID = CRHD.OBJID AND CRTX.OBJTY = CRHD.OBJTY",
  "guide": "תיאורי המשאב הרב-לשוניים המוצגים בפעולות ובלוח התזמון.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Work Center"),
  "fields": [("OBJTY","Object type","סוג אובייקט","CHAR","2","PK/FK"),
             ("OBJID","Object ID","מזהה אובייקט","NUMC","8","PK/FK"),
             ("SPRAS","Language key","שפה","LANG","1","PK"),
             ("KTEXT","Description","תיאור","CHAR","40","-")]},
 {"name": "CRCO", "he": "שיוך משאב למרכז עלות", "en": "Work center to cost center assignment",
  "tcodes": "CRC2 (Costing)", "join": "FROM CRCO JOIN CRHD ON CRCO.OBJID = CRHD.OBJID AND CRCO.OBJTY = CRHD.OBJTY",
  "guide": "מקשר את המשאב למרכז עלות ולסוגי פעילות (Activity Types) - בסיס לתמחיר שעות מכונה/עבודה בפק\"ע ולהתחשבנות ב-ACDOCA.",
  "s4": "התחשבנות ב-Universal Journal (ACDOCA); הקצאה נשמרת.",
  "help": (H, "SAP Help - Work Center Costing"),
  "fields": [("OBJTY","Object type","סוג אובייקט","CHAR","2","PK/FK"),
             ("OBJID","Object ID","מזהה אובייקט","NUMC","8","PK/FK"),
             ("LANUM","Sequence number","מספר רצף","NUMC","3","PK"),
             ("KOKRS","Controlling area","אזור בקרה","CHAR","4","FK"),
             ("KOSTL","Cost center","מרכז עלות","CHAR","10","FK"),
             ("LSTAR","Activity type","סוג פעילות","CHAR","6","FK")]},
 {"name": "CRCA", "he": "הקצאת קיבולת למשאב", "en": "Work center capacity allocation",
  "tcodes": "CR11/CR12; CRC2", "join": "FROM CRCA JOIN CRHD ON CRCA.OBJID = CRHD.OBJID AND CRCA.OBJTY = CRHD.OBJTY",
  "guide": "מקשר את המשאב לקיבולת (KAKO) - שעות זמינות ביום/משמרת. בסיס לתכנון עומסים ולתזמון פק\"ע בקו.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Capacity"),
  "fields": [("OBJTY","Object type","סוג אובייקט","CHAR","2","PK/FK"),
             ("OBJID","Object ID","מזהה אובייקט","NUMC","8","PK/FK"),
             ("CAPID","Capacity category","קטגוריית קיבולת","CHAR","3","PK"),
             ("KAPID","Capacity ID","מזהה קיבולת","NUMC","8","FK")]},
 {"name": "KAKO", "he": "כותרת קיבולת", "en": "Capacity header",
  "tcodes": "CR11/CR12/CR13", "join": "FROM KAKO JOIN CRCA ON KAKO.KAPID = CRCA.KAPID",
  "guide": "מגדיר את הקיבולת עצמה: לוח משמרות, ניצולת (%), מספר יחידות. קובע את הזמינות בפועל של קו הייצור.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Capacity Header"),
  "fields": [("KAPID","Capacity ID","מזהה קיבולת","NUMC","8","PK"),
             ("KAPAR","Capacity category","קטגוריית קיבולת","CHAR","3","-"),
             ("AZNOR","Number of individual capacities","מספר יחידות קיבולת","DEC","3","-"),
             ("NGRAD","Capacity utilization (%)","ניצולת קיבולת","DEC","3","-")]},
 {"name": "CRFH", "he": "אב כלי עזר ייצור (PRT)", "en": "Production resource/tool master",
  "tcodes": "CF01/CF02/CF03", "join": "FROM FHMI JOIN CRFH ON FHMI.FHMNR = CRFH.FHMNR",
  "guide": "רשומת אב של כלי עזר ייצור (PRT) - תבניות מילוי, פורמטים, מסננים. כולל נתוני כיול וזמינות לשיבוץ במתכון.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - PRT Master"),
  "fields": [("OBJTY","Object type (F=PRT)","סוג אובייקט","CHAR","2","PK"),
             ("OBJID","Object ID","מזהה אובייקט","NUMC","8","PK"),
             ("FHMNR","PRT number","מספר כלי עזר","CHAR","18","-"),
             ("FHMART","PRT category","קטגוריית כלי עזר","CHAR","1","-")]},
 {"name": "CRVD_A", "he": "ברירות מחדל למשאב (PI)", "en": "Resource default values",
  "tcodes": "CRC2", "join": "FROM CRVD_A JOIN CRHD ON CRVD_A.OBJID = CRHD.OBJID",
  "guide": "ערכי ברירת מחדל ספציפיים למשאב PI (מפתח בקרה, סוג פעילות) - מאיצים תחזוקת מתכונים אחידה בקו.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Resource Defaults"),
  "fields": [("OBJTY","Object type","סוג אובייקט","CHAR","2","PK/FK"),
             ("OBJID","Object ID","מזהה אובייקט","NUMC","8","PK/FK"),
             ("STEUS","Default control key","מפתח בקרה","CHAR","4","FK")]},
 {"name": "CSLA", "he": "סוגי פעילות למרכז עבודה", "en": "Activity types for work center",
  "tcodes": "KP26; CRC2", "join": "FROM CSLA JOIN CRCO ON CSLA.LSTAR = CRCO.LSTAR",
  "guide": "מגדיר את סוגי הפעילות (שעת מכונה, שעת אדם, אנרגיה) ותעריפיהם - בסיס לתמחיר עלות ייצור משתנה ב-CBC.",
  "s4": "תעריפים ב-Universal Journal; הגדרה נשמרת.",
  "help": (H, "SAP Help - Activity Types"),
  "fields": [("LSTAR","Activity type","סוג פעילות","CHAR","6","PK"),
             ("KOKRS","Controlling area","אזור בקרה","CHAR","4","PK"),
             ("LEINH","Activity unit","יחידת פעילות","UNIT","3","-")]},
 {"name": "KAZT", "he": "מרווחי קיבולת זמינה", "en": "Capacity available intervals",
  "tcodes": "CR11/CR12/CR13", "join": "FROM KAZT JOIN KAKO ON KAZT.KAPID = KAKO.KAPID",
  "guide": "מגדיר את הקיבולת הזמינה בפועל לאורך זמן (לפי משמרת/יום/מרווח) - שעות המכונה הזמינות לתזמון פק\"ע בקו. בסיס לתכנון עומסים מדויק (CM01) ולזיהוי צווארי בקבוק.",
  "s4": "ללא שינוי מבני.",
  "help": (H, "SAP Help - Available Capacity"),
  "fields": [("KAPID","Capacity ID","מזהה קיבולת","NUMC","8","PK/FK"),
             ("VERSN","Capacity version","גרסת קיבולת","NUMC","3","PK"),
             ("TPROG","Shift sequence / grouping","רצף משמרות","CHAR","2","-"),
             ("BEGZT","Start time","שעת התחלה","TIMS","6","-"),
             ("ENDZT","End time","שעת סיום","TIMS","6","-"),
             ("KAPAZ","Available capacity","קיבולת זמינה","DEC","11","-")]},
]},
# ===================== 6. PROCESS ORDER & CONTROL RECIPE ===================
{"title": "6. פק\"ע ייצור ומתכון בקרה (Process Order)", "theme": "trans", "tables": [
 {"name": "AUFK", "he": "נתוני אב של פקודת ייצור", "en": "Order master data",
  "tcodes": "COR1/COR2/COR3; COOIS", "join": "(header - process order master)",
  "guide": "כותרת פק\"ע הייצור (Process Order). נוצרת מגרסת ייצור (MKAL) + מתכון. שחרור הפק\"ע מייצר Control Recipe ושולח הוראות תהליך לקו דרך IDoc. מעקב ב-COR2/COIO.",
  "s4": "מודל מותאם; עלויות ב-ACDOCA.",
  "help": (H, "SAP Help - Process Order"),
  "fields": [("AUFNR","Order number","מספר פק\"ע","CHAR","12","PK"),
             ("AUART","Order type","סוג פק\"ע","CHAR","4","FK"),
             ("WERKS","Plant","מפעל","CHAR","4","FK"),
             ("OBJNR","Object number (status)","מפתח אובייקט","CHAR","22","FK"),
             ("KTEXT","Description","תיאור","CHAR","40","-")]},
 {"name": "AFKO", "he": "כותרת פקודת ייצור", "en": "Order header data",
  "tcodes": "COR2", "join": "FROM AFKO JOIN AUFK ON AFKO.AUFNR = AUFK.AUFNR",
  "guide": "נתוני הייצור של הפק\"ע: כמות, מועדים, גרסת ייצור (VERID), מתכון. AUFPL מקשר לפעולות. בסיס לתזמון ולפליטת חומרים.",
  "s4": "מותאם (תואם).",
  "help": (H, "SAP Help - Order Header"),
  "fields": [("AUFNR","Order number","מספר פק\"ע","CHAR","12","PK/FK"),
             ("GAMNG","Total order quantity","כמות פק\"ע","QUAN","13","-"),
             ("GMEIN","Unit of measure","יחידת מידה","UNIT","3","FK"),
             ("VERID","Production version","גרסת ייצור","CHAR","4","FK"),
             ("AUFPL","Routing number of operations","מספר תוכנית פעולות","NUMC","10","FK"),
             ("GLTRP","Basic finish date","תאריך סיום בסיסי","DATS","8","-")]},
 {"name": "AFPO", "he": "פריט פקודת ייצור", "en": "Order item",
  "tcodes": "COR3", "join": "FROM AFPO JOIN AFKO ON AFPO.AUFNR = AFKO.AUFNR",
  "guide": "פריט הפק\"ע: החומר המיוצר, כמות, מחסן קליטה, אצווה. נקודת קליטת המוצר המוגמר למלאי.",
  "s4": "מותאם (תואם).",
  "help": (H, "SAP Help - Order Item"),
  "fields": [("AUFNR","Order number","מספר פק\"ע","CHAR","12","PK/FK"),
             ("POSNR","Order item number","מספר פריט","NUMC","6","PK"),
             ("MATNR","Material produced","חומר מיוצר","CHAR","18->40","FK"),
             ("PSMNG","Order item quantity","כמות פריט","QUAN","13","-"),
             ("CHARG","Batch","אצווה","CHAR","10","-")]},
 {"name": "AFVC", "he": "פעולות פקודת הייצור", "en": "Order operations",
  "tcodes": "COR2", "join": "FROM AFVC JOIN AFKO ON AFVC.AUFPL = AFKO.AUFPL",
  "guide": "פעולות/פאזות הפק\"ע (מועתקות מהמתכון). מפתח בקרה קובע דיווח/הוראות תהליך. בסיס לדיווח ביצוע (CORK) ולתמחיר.",
  "s4": "מותאם (תואם).",
  "help": (H, "SAP Help - Order Operations"),
  "fields": [("AUFPL","Routing number of operations","מספר תוכנית פעולות","NUMC","10","PK/FK"),
             ("APLZL","Internal counter","מונה פנימי","NUMC","8","PK"),
             ("VORNR","Operation number","מספר פעולה","CHAR","4","-"),
             ("ARBID","Resource (object id)","משאב","NUMC","8","FK"),
             ("STEUS","Control key","מפתח בקרה","CHAR","4","FK"),
             ("LTXA1","Operation text","תיאור פעולה","CHAR","40","-")]},
 {"name": "RESB", "he": "הזמנת רכיבים לפק\"ע", "en": "Reservation / dependent requirements",
  "tcodes": "COR2; CO09", "join": "FROM RESB JOIN AFKO ON RESB.AUFNR = AFKO.AUFNR",
  "guide": "הזמנות חומרי הגלם/האריזה לפק\"ע (מפיצוץ עץ המוצר). כל פליטת חומר (261) מעדכנת RESB. סנכרון עם מסופי Zetes בפליטה.",
  "s4": "ללא שינוי; תנועת מלאי ב-MATDOC.",
  "help": (H, "SAP Help - Reservation"),
  "fields": [("RSNUM","Reservation number","מספר הזמנה","NUMC","10","PK"),
             ("RSPOS","Reservation item","פריט הזמנה","NUMC","4","PK"),
             ("MATNR","Component","רכיב","CHAR","18->40","FK"),
             ("BDMNG","Requirement quantity","כמות נדרשת","QUAN","13","-"),
             ("ENMNG","Quantity withdrawn","כמות שנפלטה","QUAN","13","-"),
             ("AUFNR","Order number","מספר פק\"ע","CHAR","12","FK")]},
 {"name": "AFRU", "he": "דיווחי ביצוע פק\"ע", "en": "Order confirmations",
  "tcodes": "CORK; COR6", "join": "FROM AFRU JOIN AFKO ON AFRU.AUFNR = AFKO.AUFNR",
  "guide": "דיווחי הביצוע על פעולות הפק\"ע: כמות שיוצרה, פחת, זמני מכונה/אדם. מקור הנתונים מהקו (PI sheet/MES) ובסיס לעלות ולניתוח פחת מול 1% היעד.",
  "s4": "ללא שינוי; עלויות ב-ACDOCA.",
  "help": (H, "SAP Help - Confirmation"),
  "fields": [("RUECK","Confirmation number","מספר דיווח","NUMC","10","PK"),
             ("RMZHL","Confirmation counter","מונה דיווח","NUMC","8","PK"),
             ("AUFNR","Order number","מספר פק\"ע","CHAR","12","FK"),
             ("LMNGA","Yield (confirmed qty)","כמות שיוצרה","QUAN","13","-"),
             ("XMNGA","Scrap quantity","כמות פחת","QUAN","13","-")]},
 {"name": "AFFH", "he": "שיוך PRT לפק\"ע", "en": "PRT allocation in order",
  "tcodes": "COR2 (PRT)", "join": "FROM AFFH JOIN AFKO ON AFFH.AUFPL = AFKO.AUFPL",
  "guide": "כלי עזר הייצור (PRT) המשובצים לפק\"ע - תבניות/פורמטים נדרשים בקו לאצווה הספציפית.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - PRT in Order"),
  "fields": [("AUFPL","Routing number","מספר תוכנית פעולות","NUMC","10","PK/FK"),
             ("APLZL","Counter","מונה","NUMC","8","PK"),
             ("FHMNR","PRT number","מספר כלי עזר","CHAR","18","FK")]},
 {"name": "AFFL", "he": "רצפי פעולות בפק\"ע", "en": "Order sequences (work order)",
  "tcodes": "COR2", "join": "FROM AFFL JOIN AFKO ON AFFL.AUFPL = AFKO.AUFPL",
  "guide": "רצפי הפעולות בפק\"ע (סטנדרטי/מקביל) - מאפשר ביצוע פאזות במקביל בקו הייצור ובסיס לתזמון מדויק.",
  "s4": "מותאם (תואם).",
  "help": (H, "SAP Help - Order Sequences"),
  "fields": [("AUFPL","Routing number of operations","מספר תוכנית פעולות","NUMC","10","PK/FK"),
             ("APLFL","Sequence","רצף","CHAR","6","PK"),
             ("PLNFL","Reference sequence","רצף ייחוס","CHAR","6","-"),
             ("FLGAT","Sequence category","קטגוריית רצף","CHAR","1","-")]},
]},
# ===================== 7. CUSTOMIZING / CONFIG =============================
{"title": "7. קונפיגורציה (Customizing)", "theme": "config", "tables": [
 {"name": "T134", "he": "סוגי חומר (Customizing)", "en": "Material types",
  "tcodes": "OMS2; SPRO", "join": "FROM MARA JOIN T134 ON MARA.MTART = T134.MTART",
  "guide": "מגדיר את סוגי החומר ושולט באילו תצוגות/שדות חובה ובאיזה טווח מספרים. סיווג מזון ומשקאות ב-CBC: ROH (חומר גלם - תרכיז, סוכר, CO2, חומרי אריזה גולמיים), HALB (מוצר ביניים - בסיס משקה/סירופ מעורבב), FERT (מוצר מוגמר - בקבוק/פחית מוכן למשלוח), VERP (חומרי אריזה - תוויות, מכסים), UNBW/HAWA (לא מוערך/סחורה). כל סוג מפעיל תצוגות (Basic/MRP/Recipe/QM/Costing) ושדות חובה שונים.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Material Types"),
  "fields": [("MTART","Material type","סוג חומר","CHAR","4","PK"),
             ("MBRSH","Industry sector","ענף","CHAR","1","-"),
             ("KKREF","Account category reference","הפניית קטגוריית חשבון","CHAR","4","-")]},
 {"name": "T134T", "he": "טקסטים לסוגי חומר", "en": "Material type descriptions",
  "tcodes": "OMS2", "join": "FROM T134T JOIN T134 ON T134T.MTART = T134.MTART",
  "guide": "תיאורי סוגי החומר הרב-לשוניים.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Material Types"),
  "fields": [("MTART","Material type","סוג חומר","CHAR","4","PK/FK"),
             ("SPRAS","Language key","שפה","LANG","1","PK"),
             ("MTBEZ","Material type description","תיאור סוג חומר","CHAR","25","-")]},
 {"name": "T023", "he": "קבוצות חומר (Customizing)", "en": "Material groups",
  "tcodes": "OMSF; SPRO", "join": "FROM MARA JOIN T023 ON MARA.MATKL = T023.MATKL",
  "guide": "מגדיר קבוצות חומר לקיבוץ דיווחי וניתוח רכש/ייצור - לדוגמה 'תרכיזים', 'בקבוקי PET', 'פחיות'.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Material Groups"),
  "fields": [("MATKL","Material group","קבוצת חומר","CHAR","9","PK"),
             ("BKLAS","Valuation class","מחלקת הערכה","CHAR","4","-")]},
 {"name": "T023T", "he": "טקסטים לקבוצות חומר", "en": "Material group descriptions",
  "tcodes": "OMSF", "join": "FROM T023T JOIN T023 ON T023T.MATKL = T023.MATKL",
  "guide": "תיאורי קבוצות החומר הרב-לשוניים.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Material Groups"),
  "fields": [("MATKL","Material group","קבוצת חומר","CHAR","9","PK/FK"),
             ("SPRAS","Language key","שפה","LANG","1","PK"),
             ("WGBEZ","Material group description","תיאור קבוצת חומר","CHAR","20","-")]},
 {"name": "T399X", "he": "פרמטרי בקרת ייצור למפעל", "en": "Plant production control parameters",
  "tcodes": "OPL8; SPRO", "join": "FROM AUFK JOIN T399X ON AUFK.WERKS = T399X.WERKS AND AUFK.AUART = T399X.AUART",
  "guide": "פרמטרי בקרה לפק\"ע לפי מפעל/סוג פק\"ע: זמינות, אופק שחרור, פרופיל סטטוס, IDoc. כאן מוגדרת זרימת ה-Control Recipe ל-Zetes/Daymax.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Order Type Plant Parameters"),
  "fields": [("WERKS","Plant","מפעל","CHAR","4","PK"),
             ("AUART","Order type","סוג פק\"ע","CHAR","4","PK"),
             ("APROFIL","Availability check profile","פרופיל בדיקת זמינות","CHAR","4","-"),
             ("TERHO","Scheduling / release horizon","אופק שחרור","NUMC","3","-")]},
 {"name": "TCK03", "he": "וריאנט תמחיר (Costing Variant)", "en": "Costing variant",
  "tcodes": "OKKN; SPRO", "join": "FROM T399X JOIN TCK03 ON T399X.KLVARP = TCK03.KLVAR",
  "guide": "מגדיר את וריאנט התמחיר המתוכנן/בפועל של פק\"ע (אסטרטגיית מחיר, אזור). בסיס לחישוב עלות התקן של משקה.",
  "s4": "תואם; הערכה ב-Material Ledger/ACDOCA.",
  "help": (H, "SAP Help - Costing Variant"),
  "fields": [("KLVAR","Costing variant","וריאנט תמחיר","CHAR","4","PK"),
             ("BWVAR","Valuation variant","וריאנט הערכה","CHAR","3","-"),
             ("KALAW","Costing type","סוג תמחיר","CHAR","2","-")]},
 {"name": "T438M", "he": "פרמטרי MRP לחומר/מפעל", "en": "MRP control parameters",
  "tcodes": "OPPQ; SPRO", "join": "FROM MARC JOIN T438M ON MARC.DISMM = T438M.DISMM",
  "guide": "פרמטרי בקרת MRP (סוג תכנון, גודל אצווה) - שולטים בתכנון אוטומטי של חומרי גלם וייצור ב-MRP Live.",
  "s4": "MRP Live - חלק מהפרמטרים מותאמים; אמת מול SAP Help.",
  "help": (H, "SAP Help - MRP Parameters"),
  "fields": [("DISMM","MRP type","סוג MRP","CHAR","2","PK"),
             ("DISVF","MRP procedure","שיטת MRP","CHAR","1","-")]},
 {"name": "T003O", "he": "סוגי פקודת ייצור (Process Order Types)", "en": "Order types (process orders)",
  "tcodes": "COR4; SPRO", "join": "FROM AUFK JOIN T003O ON AUFK.AUART = T003O.AUART",
  "guide": "מגדיר סוגי פק\"ע ייצור (PI01 תהליך, PI02 שיפוץ) - קטגוריה, טווח מספרים ופרופיל סטטוס. ב-CBC מפריד תהליכי ייצור (ערבול/מילוי) מתהליכי תחזוקה. שחרור הפק\"ע מפעיל IDoc LOIPRO לקו.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Order Types"),
  "fields": [("AUART","Order type","סוג פק\"ע","CHAR","4","PK"),
             ("AUTYP","Order category (40=process)","קטגוריית פק\"ע","NUMC","2","-"),
             ("STSMA","Status profile","פרופיל סטטוס","CHAR","8","FK"),
             ("NUMKI","Internal number range","טווח מספרים פנימי","CHAR","2","-")]},
 {"name": "TCO01", "he": "פרמטרים תלויי סוג פק\"ע (Order Profile)", "en": "Order type-dependent parameters",
  "tcodes": "COR4; SPRO", "join": "FROM TCO01 JOIN T003O ON TCO01.AUART = T003O.AUART",
  "guide": "פרמטרי ברירת מחדל לפק\"ע לפי סוג/מפעל: וריאנט תמחיר, פרופיל זמינות, פרופיל שחרור Control Recipe ל-MES. כאן מוגדרת זרימת ההוראות ל-Zetes/Daymax.",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Order Parameters"),
  "fields": [("WERKS","Plant","מפעל","CHAR","4","PK"),
             ("AUART","Order type","סוג פק\"ע","CHAR","4","PK/FK"),
             ("KLVARP","Costing variant (plan)","וריאנט תמחיר מתוכנן","CHAR","4","FK"),
             ("APROF","Availability check profile","פרופיל בדיקת זמינות","CHAR","4","-")]},
 {"name": "TJ30", "he": "סטטוסי משתמש בפרופיל (User Status)", "en": "User status within profile",
  "tcodes": "BS02/BS03", "join": "FROM JEST JOIN TJ30 ON JEST.STAT = TJ30.ESTAT",
  "guide": "מגדיר סטטוסי משתמש מותאמים (למשל 'אושר QA', 'ממתין חומר') וחסימת/התרת תהליכים. ב-CBC אוכף תהליכי עבודה ברמת התא/קו (cell-level) - חוסם שחרור פק\"ע עד אישור.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Status Management"),
  "fields": [("STSMA","Status profile","פרופיל סטטוס","CHAR","8","PK"),
             ("ESTAT","User status","סטטוס משתמש","CHAR","5","PK"),
             ("VRGNG","Business transaction","תהליך עסקי","CHAR","8","-"),
             ("ANWND","Application (PP)","יישום","CHAR","8","-")]},
 {"name": "TJ30T", "he": "טקסטים לסטטוסי משתמש", "en": "User status texts",
  "tcodes": "BS02/BS03", "join": "FROM TJ30T JOIN TJ30 ON TJ30T.STSMA = TJ30.STSMA AND TJ30T.ESTAT = TJ30.ESTAT",
  "guide": "התיאורים הרב-לשוניים (עברית/אנגלית) של סטטוסי המשתמש - חיוני לתצוגה דו-לשונית בלוח הייצור (COIO).",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Status Texts"),
  "fields": [("STSMA","Status profile","פרופיל סטטוס","CHAR","8","PK/FK"),
             ("ESTAT","User status","סטטוס משתמש","CHAR","5","PK/FK"),
             ("SPRAS","Language key","שפה","LANG","1","PK"),
             ("TXT04","Short code","קוד מקוצר","CHAR","4","-"),
             ("TXT30","Status text","תיאור סטטוס","CHAR","30","-")]},
 {"name": "BUT000", "he": "שותף עסקי (BP - השפעת מעבר S/4)", "en": "Business Partner general data",
  "tcodes": "BP; (ECC: XK01/MK01)", "join": "FROM EKKO JOIN BUT000 ON EKKO.LIFNR = BUT000.PARTNER",
  "guide": "ב-S/4HANA ספקי חומרי הגלם/אריזה של CBC מנוהלים כ-Business Partner (BP) במקום ספק קלאסי. נדרש CVI להמרת LFA1->BUT000 לפני ההמרה. כל רכש חומר גלם לייצור מצריך BP פעיל עם תפקיד ספק (FLVN01).",
  "s4": "הוחלף - Business Partner חובה (CVI); ראה SAP Note 2265093.",
  "help": (NOTE(2265093), "SAP Note 2265093 (BP)"),
  "fields": [("PARTNER","Business partner number","מספר שותף עסקי","CHAR","10","PK"),
             ("TYPE","BP category","קטגוריית שותף","CHAR","1","-"),
             ("BU_GROUP","BP grouping","קבוצת שותף","CHAR","4","FK"),
             ("BPKIND","BP type","סוג שותף","CHAR","4","-"),
             ("NAME_ORG1","Organization name","שם ארגון","CHAR","40","-")]},
 {"name": "TC22", "he": "מפתחות בקרת תהליך/פעולה (PI Control)", "en": "Process/operation control keys config",
  "tcodes": "SPRO; OPL8", "join": "FROM PLPO JOIN TC22 ON PLPO.STEUS = TC22.STEUS",
  "guide": "הגדרת מפתחות הבקרה (STEUS) הקובעים אם פעולה מפעילה הוראות תהליך (PI), דיווח, תמחיר או רכש חיצוני. לב חיבור ה-PP-PI לאוטומציית הקו. (אמת מול SE11 - מפתחות בקרה גם ב-TC30).",
  "s4": "ללא שינוי (Customizing).",
  "help": (H, "SAP Help - Control Keys"),
  "fields": [("STEUS","Control key","מפתח בקרה","CHAR","4","PK"),
             ("RUECK","Confirmation indicator","מחוון דיווח","CHAR","1","-"),
             ("BANFK","External processing (PReq)","עיבוד חיצוני","CHAR","1","-"),
             ("PROZESS","Process instruction indicator","מחוון הוראות תהליך","CHAR","1","-")]},
 {"name": "JEST", "he": "סטטוס אובייקט - מכונת מצבים של הפק\"ע", "en": "Individual object status (state machine)",
  "tcodes": "COR3 (status); BS22/BS23", "join": "FROM JEST JOIN AUFK ON JEST.OBJNR = AUFK.OBJNR",
  "guide": "מנהל כל סטטוס מערכת/משתמש פעיל לאובייקט (פק\"ע/מתכון). מחזור חיי פק\"ע הייצור: CRTE (נוצר) -> REL (שוחרר) -> PCNF/CNF (דווח חלקית/מלא) -> TECO (הושלם טכנית) -> DLV (סופק) -> CLSD (סגור). הסטטוס שולט בפעולות המותרות בקו (שחרור Control Recipe, פליטת חומר, דיווח). I0002=REL, I0009=TECO.",
  "s4": "ללא שינוי; ניהול סטטוס זהה ב-S/4.",
  "help": (H, "SAP Help - Status Management"),
  "fields": [("OBJNR","Object number","מפתח אובייקט","CHAR","22","PK/FK"),
             ("STAT","System/user status (I0002=REL...)","סטטוס מערכת/משתמש","CHAR","5","PK"),
             ("INACT","Status inactive indicator","מחוון לא-פעיל","CHAR","1","-"),
             ("CHGNR","Change number","מספר שינוי","CHAR","6","-")]},
 {"name": "JSTO", "he": "כותרת אובייקט סטטוס + פרופיל", "en": "Status object header + profile",
  "tcodes": "BS02/BS03", "join": "FROM JSTO JOIN AUFK ON JSTO.OBJNR = AUFK.OBJNR",
  "guide": "כותרת אובייקט הסטטוס - מקשרת את הפק\"ע לפרופיל הסטטוס (STSMA) ולסוג האובייקט. דרכה נאכפים סטטוסי המשתמש של CBC לבקרת תהליכי הקו.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - Status Object"),
  "fields": [("OBJNR","Object number","מפתח אובייקט","CHAR","22","PK"),
             ("STSMA","Status profile","פרופיל סטטוס","CHAR","8","FK"),
             ("OBTYP","Object type","סוג אובייקט","CHAR","2","-"),
             ("CHGKZ","Change flag","מחוון שינוי","CHAR","1","-")]},
 {"name": "TJ02T", "he": "טקסטים של סטטוסי מערכת (CRTE/REL/CNF/TECO)", "en": "System status texts",
  "tcodes": "BS23", "join": "FROM JEST JOIN TJ02T ON JEST.STAT = TJ02T.ISTAT",
  "guide": "טבלת הפענוח של סטטוסי המערכת הקבועים: CRTE (Created), REL (Released), PCNF (Part. confirmed), CNF (Confirmed), TECO (Tech. completed), DLV (Delivered), CLSD (Closed). חיונית לדוחות מחזור חיים ולפענוח שדה STAT.",
  "s4": "ללא שינוי.",
  "help": (H, "SAP Help - System Status"),
  "fields": [("ISTAT","Internal system status","סטטוס מערכת פנימי","CHAR","5","PK"),
             ("SPRAS","Language key","שפה","LANG","1","PK"),
             ("TXT04","Status code (CRTE/REL/CNF/TECO)","קוד סטטוס מקוצר","CHAR","4","-"),
             ("TXT30","Status description","תיאור סטטוס","CHAR","30","-")]},
]},
]

# ===========================================================================
#  OPERATIONAL LAYER (per topic, aligned to TOPICS order) - the foundation
#  before field lists: T-code -> Fiori mapping, Interfaces (BAPI/IDoc/RFC),
#  and standard background programs / reports.
# ===========================================================================
OPS = [
# 1 - Material Master & UoM
 {"tcodes": [("MM01 / MM02 / MM03","Manage Product Master Data","F1602A"),
             ("MM50 (extend views)","Manage Product Master Data","F1602A"),
             ("MMSC (ext. storage loc.)","Mass Maintenance - Products","-"),
             ("CUNI (UoM config)","Configure Units of Measure (SPRO)","-")],
  "interfaces": [("BAPI","BAPI_MATERIAL_SAVEDATA","יצירה/עדכון אב חומר - ליבת הטעינה ההמונית והממשקים"),
                 ("BAPI","BAPI_MATERIAL_GET_DETAIL","שליפת נתוני חומר לדוחות/ממשקים"),
                 ("IDoc","MATMAS (MATMAS05)","הפצת אב חומר ל/מ-מערכות חיצוניות (Zetes/Daymax)"),
                 ("RFC","MARA_SINGLE_READ / MARC_SINGLE_READ","קריאת חומר/מפעל בודד")],
  "programs": [("RMMG2000","טעינה/עדכון חומר המוני (Direct Input)"),
               ("RMDATIND","Direct Input לאב חומר מממשק"),
               ("RMMM00B0 / MM60","דוח רשימת חומרים")]},
# 2 - BOM
 {"tcodes": [("CS01 / CS02 / CS03","Maintain Bill of Material","F1743"),
             ("CS11 / CS12 / CS15","Manage Material BOMs","F1813"),
             ("CEWB (eng. workbench)","Manage Bill of Materials","F1813")],
  "interfaces": [("BAPI","BAPI_MATERIAL_BOM_GROUP_CREATE","יצירת עץ מוצר (S/4 BOM API)"),
                 ("FM","CSAP_MAT_BOM_MAINTAIN","תחזוקת עץ מוצר (ECC)"),
                 ("IDoc","BOMMAT","הפצת עץ מוצר חומר בין מערכות"),
                 ("RFC","CS_BOM_EXPL_MAT_RC1","פיצוץ עץ מוצר לחומר")],
  "programs": [("RCSBOM00","עיבוד/בדיקת עצי מוצר המוני"),
               ("RCSBI010","פיצוץ עץ מוצר רב-רמתי"),
               ("CS_BT","דוח Where-Used לרכיב")]},
# 3 - Master Recipe & Operations
 {"tcodes": [("C201 / C202 / C203","Manage Master Recipes","-"),
             ("C251 (print)","Master Recipe Print","-"),
             ("COIO (production cockpit)","Process Order Information System","-")],
  "interfaces": [("RFC","CP_RECIPE_READ","קריאת מתכון ייצור"),
                 ("BAPI","BAPI_CENTRAL_CHARACT_CREATE","יצירת מאפיין בדיקה ראשי (QM)"),
                 ("IDoc","LOIPRO","הוראות ייצור - מהמתכון לפק\"ע ולקו"),
                 ("PI","Control Recipe / PI Sheet (PI Messages)","שליחת הוראות תהליך לבקר/MES (Zetes/Daymax)")],
  "programs": [("RCEXMASS","עיבוד המוני מתכונים"),
               ("RCPRECIPE","דוח/הערכת מתכונים"),
               ("RCO_CONTROL_RECIPE","יצירת/שליחת Control Recipe")]},
# 4 - Production Versions
 {"tcodes": [("C223","Manage Production Versions","F2703"),
             ("MM02 (PV tab)","Manage Product Master Data","F1602A"),
             ("CC01/CC02 (ECM)","Manage Change Records","-")],
  "interfaces": [("BAPI","BAPI_MATERIAL_SAVEDATA (PVERSIONS)","יצירה/עדכון גרסת ייצור"),
                 ("BAPI","BAPI_PRODVERS_CREATE_REPLACE","יצירה/החלפת גרסת ייצור (אמת)"),
                 ("FM","CM_FV_PROD_VERS_READ","קריאת גרסאות ייצור לחומר/מפעל")],
  "programs": [("RCC22300 / RSC22300","בדיקת עקביות המונית של גרסאות ייצור (Pre-check ל-S/4)"),
               ("CS_BD_DIRECT_LINK","יצירת קישור ישיר BOM<->Recipe לגרסה")]},
# 5 - Resources / Work Centers
 {"tcodes": [("CRC1 / CRC2 / CRC3","Manage Work Centers / Resources","F3794"),
             ("CR11 / CR12 / CR13","Manage Capacity","-"),
             ("KP26 (activity rates)","Manage Cost Rates","-")],
  "interfaces": [("RFC","CR_WORK_CENTER_READ","קריאת נתוני מרכז עבודה/משאב"),
                 ("FM","CRAP_WORKCENTER_GET_DETAIL","שליפת פרטי משאב"),
                 ("FM","CY_CAPACITY_LOAD","חישוב עומס קיבולת")],
  "programs": [("RCCRSE00 / CR05","דוח מרכזי עבודה/משאבים"),
               ("RIABC000","ניתוח קיבולת / ABC (אמת)"),
               ("RCCYPL00 / CM01","הערכת עומסי קיבולת")]},
# 6 - Process Order & Control Recipe
 {"tcodes": [("COR1 / COR2 / COR3","Create / Change / Display Process Order","-"),
             ("COR6N (confirm)","Confirm Production Operation","F3372"),
             ("COIO / COOIS","Process Order Information System","-"),
             ("COHV (mass proc.)","Mass Processing - Orders","-")],
  "interfaces": [("BAPI","BAPI_PROCORD_CREATE / _RELEASE","יצירה/שחרור פק\"ע ייצור"),
                 ("BAPI","BAPI_PROCORDCONF_CREATE_TT","דיווח ביצוע פק\"ע (Time Ticket)"),
                 ("IDoc","LOIPRO","שליחת פק\"ע/הוראות ייצור ל-MES (Zetes/Daymax)"),
                 ("IDoc","PPCC1 (PP-PI message)","הודעות תהליך/דיווח מהקו חזרה ל-SAP")],
  "programs": [("MD01 / MD01N (MRP Live)","הרצת MRP - תכנון חומרים וייצור"),
               ("COHV / RCO_BATCH_SCHEDULE","עיבוד המוני ותזמון אצוות פק\"ע"),
               ("CO41 / CO48 (convert)","המרת פק\"ע מתוכננת לפק\"ע ייצור")]},
# 7 - SPRO Customizing & Configuration
 {"tcodes": [("COR4 (order type)","Configure Order Types (SPRO)","-"),
             ("OPL8 (plant params)","Order Type-Dependent Parameters","-"),
             ("BS02 (status profile)","Maintain Status Profile","-"),
             ("BP (Business Partner)","Manage Business Partner Master Data","-")],
  "interfaces": [("IDoc","LOIPRO","פק\"ע/הוראות ייצור ל-MES"),
                 ("BAPI","BAPI_BUPA_CREATE_FROM_DATA","יצירת שותף עסקי (BP)"),
                 ("FM","CVI_VENDOR_TO_BP_CONVERT","המרת ספק ל-BP (CVI)"),
                 ("RFC","STATUS_CHANGE_INTERN","שינוי סטטוס פנימי")],
  "programs": [("RBDMIDOC","יצירת IDocs להפצה (MATMAS/LOIPRO)"),
               ("MDS_LOAD_COCKPIT","סנכרון Customer/Vendor Integration ל-BP"),
               ("RHALTD00 / RCOZP","עיבוד/בדיקת קונפיגורציה")]},
]

# ===========================================================================
#  PP (Discrete) vs PP-PI (Process Industries) - enterprise education matrix
#  (aspect, SAP PP discrete, SAP PP-PI process, CBC / S4 note)
# ===========================================================================
PPVS = [
 ("סוג ייצור (Production type)", "ייצור בדיד / יחידות (Discrete)",
  "ייצור תהליכי / אצוות ונוזלים (Process)",
  "CBC: ייצור משקאות הוא תהליכי מובהק - PP-PI הוא המודול הנכון (לא PP בדיד)."),
 ("ענפים אופייניים (Industries)", "רכב, אלקטרוניקה, מכונות, הרכבה",
  "מזון ומשקאות, כימיה, פארמה, קוסמטיקה",
  "CBC (Coca-Cola) נמצא בליבת ה-Process Industries."),
 ("נתוני אב חומר (Material)", "חומר סטנדרטי (לרוב ללא אצווה)",
  "חומר מנוהל אצווה (Batch-managed) - חובה",
  "כל תרכיז/מוצר ב-CBC מנוהל אצווה לניהול BBD/תפוגה ומעקב Track&Trace."),
 ("הוראת ייצור (Order)", "Production Order - CO01 / CO02 / CO03",
  "Process Order - COR1 / COR2 / COR3",
  "שחרור Process Order מפעיל Control Recipe ו-IDoc LOIPRO ל-MES."),
 ("רשימת פעולות (Routing/Recipe)", "Routing - CA01 / CA02 / CA03",
  "Master Recipe (מתכון ייצור) - C201 / C202 / C203",
  "המתכון כולל נוסחה (Formula), פאזות והוראות תהליך - לא רק פעולות."),
 ("מבנה ביצוע (Execution structure)", "Operations (פעולות בלבד)",
  "Operations + Phases + Process Instructions (PI)",
  "הפאזות (ערבול/פסטור/מילוי) שולחות הוראות לבקרי הקו."),
 ("משאבי ביצוע (Resources)", "Work Center - CR01 / CR02 / CR03",
  "Resource - CRC1 / CRC2 / CRC3",
  "אותו מודל טכני (CRHD) אך ה-Resource נושא ערכי PI וברירות מחדל לתהליך."),
 ("בקרת ביצוע (Shop-floor control)", "דיווח ביצוע (Confirmation) ידני/MES",
  "Control Recipe / PI Sheet / Process Messages",
  "PP-PI מתממשק ל-Zetes/Daymax דרך הודעות תהליך (PI Messages) ו-IDoc."),
 ("מערכת מעקב (Monitoring cockpit)", "COOIS (Order Information System)",
  "COIO (Process Order Information System) + PI Cockpit",
  "COIO הוא לוח המעקב התפעולי המרכזי של CBC."),
 ("עץ מוצר (BOM)", "Production BOM (STLAN=1)",
  "Recipe BOM + שיוך רכיב לפאזה (PLMZ)",
  "ב-PP-PI כל חומר גלם משויך לפאזה הספציפית שבה הוא נצרך."),
 ("גרסת ייצור (Production Version)", "MKAL - מומלצת ב-ECC",
  "MKAL - חובה 100% ב-S/4HANA",
  "ב-S/4 ה-VERID נועל את הקישור המדויק מתכון<->BOM חלופי לכל ביצוע."),
 ("תכנון חומרים (Planning)", "MRP קלאסי - MD01 / NETCH",
  "MRP Live (HANA-optimized) - MD01N",
  "ב-S/4 ריצות ה-MRP הקלאסיות מוחלפות ב-MRP Live שרץ ישירות על HANA."),
 ("ממשק חיצוני (IDoc/MES)", "LOIPRO (Production Order)",
  "LOIPRO + PI Process Messages (PPCC1)",
  "סנכרון דו-כיווני בין SAP לבין מערכות הלוגיסטיקה/אוטומציה (Zetes/Daymax)."),
 ("עלות והערכה (Costing)", "Order settlement -> CO",
  "Order settlement -> Universal Journal (ACDOCA)",
  "ב-S/4 Material Ledger חובה; עלויות הפק\"ע זורמות ל-ACDOCA."),
]

# ===========================================================================
#  PER-TABLE Functions/BAPIs + Background Programs (PM-grade encyclopedic depth)
#  Tables not listed fall back to the stream default (by theme) - zero omissions.
# ===========================================================================
STREAM_FUNCS = {
 "master": [("BAPI_MATERIAL_SAVEDATA", "יצירה/עדכון נתוני חומר"), ("BAPI_MATERIAL_GET_DETAIL", "שליפת פרטי חומר")],
 "trans":  [("BAPI_PROCORD_CREATE", "יצירת פק\"ע ייצור"), ("BAPI_PROCORD_GET_DETAIL", "שליפת פרטי פק\"ע")],
 "config": [("VIEW_MAINTENANCE_CALL (SM30)", "תחזוקת טבלת קונפיגורציה"), ("RFC_READ_TABLE", "קריאת תוכן הטבלה")],
 "cross":  [("BAPI_MATERIAL_SAVEDATA", "עדכון נתוני אב משולבים")],
}
STREAM_PROGS = {
 "master": [("RMMG2000", "עדכון/טעינת חומר המוני (Direct Input)"), ("MM60", "רשימת חומרים")],
 "trans":  [("COOIS / COHV", "רשימת ועיבוד המוני פק\"ע")],
 "config": [("SE16N / table display", "עיון בתוכן טבלת הקונפיגורציה")],
 "cross":  [("RCC22300", "בדיקת עקביות גרסאות ייצור")],
}
FUNCS = {
 "MARA": [("BAPI_MATERIAL_SAVEDATA", "יצירה/עדכון אב חומר"), ("BAPI_MATERIAL_GET_DETAIL", "שליפת פרטי חומר"),
          ("BAPI_MATERIAL_EXISTENCECHECK", "בדיקת קיום חומר")],
 "MAKT": [("BAPI_MATERIAL_SAVEDATA", "עדכון תיאורי חומר"), ("MAKT_SINGLE_READ", "קריאת תיאור חומר")],
 "MARC": [("BAPI_MATERIAL_SAVEDATA", "עדכון נתוני מפעל"), ("MARC_SINGLE_READ", "קריאת נתוני מפעל")],
 "MARM": [("BAPI_MATERIAL_SAVEDATA", "עדכון המרות UoM"), ("MATERIAL_UNIT_CONVERSION", "המרת כמות בין יחידות + עיגול"),
          ("MD_CONVERT_MATERIAL_UNIT", "חישוב מקדם המרה (1% פחת)")],
 "MBEW": [("BAPI_MATERIAL_SAVEDATA", "עדכון הערכה"), ("CKMVFM_MATERIAL_PRICE_READ", "קריאת מחיר חומר")],
 "MCH1": [("BAPI_BATCH_CREATE", "יצירת אצווה"), ("VB_BATCH_DETAIL_GET", "שליפת פרטי אצווה"),
          ("BAPI_BATCH_GET_DETAIL", "שליפת אצווה (BBD)")],
 "MCHA": [("VB_BATCH_VERIFY", "אימות אצווה במפעל")],
 "T006": [("UNIT_CONVERSION_SIMPLE", "המרת יחידות"), ("DIMENSION_GET", "שליפת מימד יחידה")],
 "MAST": [("CSAP_MAT_BOM_READ", "קריאת קישור חומר-BOM")],
 "STKO": [("BAPI_MATERIAL_BOM_GROUP_CREATE", "יצירת עץ מוצר (S/4)"), ("CSAP_MAT_BOM_MAINTAIN", "תחזוקת עץ מוצר")],
 "STPO": [("BAPI_MATERIAL_BOM_GROUP_CREATE", "יצירת פריטי עץ מוצר"), ("CS_BOM_EXPL_MAT_RC1", "פיצוץ עץ מוצר")],
 "PLKO": [("BAPI_ROUTING_CREATE", "יצירת רשימת פעולות/מתכון"), ("CP_RECIPE_READ", "קריאת מתכון ייצור")],
 "PLPO": [("CP_DI_OPERATION_READ", "קריאת פעולות/פאזות"), ("BAPI_ROUTING_GETDETAIL", "שליפת פרטי מתכון")],
 "PLMK": [("BAPI_CENTRAL_CHARACT_CREATE", "יצירת מאפיין בדיקה"), ("QPK1_INSPCHAR_READ", "קריאת מאפייני בדיקה")],
 "MKAL": [("BAPI_MATERIAL_SAVEDATA (PVERSIONS)", "עדכון גרסת ייצור"),
          ("BAPI_PRODVERS_CREATE_REPLACE", "יצירה/החלפת גרסת ייצור (אמת)"),
          ("CM_FV_PROD_VERS_READ", "קריאת גרסאות ייצור לחומר/מפעל")],
 "CRHD": [("CR_WORK_CENTER_READ", "קריאת משאב/מרכז עבודה"), ("CRAP_WORKCENTER_GET_DETAIL", "שליפת פרטי משאב")],
 "CRCO": [("CR_COST_CENTER_READ", "קריאת שיוך מרכז עלות")],
 "KAKO": [("CY_CAPACITY_HEADER_READ", "קריאת כותרת קיבולת")],
 "AUFK": [("BAPI_PROCORD_CREATE", "יצירת פק\"ע ייצור"), ("BAPI_PROCORD_RELEASE", "שחרור פק\"ע (REL)"),
          ("BAPI_PROCORD_GET_DETAIL", "שליפת פרטי פק\"ע")],
 "AFKO": [("BAPI_PROCORD_CREATE", "יצירת פק\"ע"), ("BAPI_PROCORD_GET_LIST", "שליפת רשימת פק\"ע")],
 "AFRU": [("BAPI_PROCORDCONF_CREATE_TT", "דיווח ביצוע (Time Ticket)"), ("BAPI_PROCORDCONF_GETLIST", "רשימת דיווחים")],
 "RESB": [("BAPI_RESERVATION_CREATE1", "יצירת הזמנת רכיבים"), ("BAPI_GOODSMVT_CREATE", "פליטת חומר לפק\"ע (261)")],
 "JEST": [("STATUS_READ", "קריאת סטטוסי אובייקט פעילים"), ("STATUS_CHANGE_INTERN", "שינוי סטטוס מערכת פנימי")],
 "JSTO": [("STATUS_OBJECT_CREATE", "יצירת אובייקט סטטוס"), ("STATUS_PROFILE_READ", "קריאת פרופיל סטטוס")],
 "TJ02T": [("STATUS_TEXT_READ", "קריאת טקסט סטטוס מערכת")],
 "TJ30": [("STATUS_CHANGE_EXTERN", "שינוי סטטוס משתמש"), ("USER_STATUS_CHECK", "בדיקת סטטוס משתמש מותר")],
 "BUT000": [("BAPI_BUPA_CREATE_FROM_DATA", "יצירת שותף עסקי"), ("CVI_VENDOR_TO_BP_CONVERT", "המרת ספק ל-BP (CVI)")],
 "T003O": [("CO_BT_ORDER_TYPE_CHECK", "בדיקת סוג פק\"ע")],
}
PROGS = {
 "MARA": [("RMMG2000", "טעינת/עדכון חומר המוני"), ("RMDATIND", "Direct Input לאב חומר")],
 "MARM": [("RMMM00B0", "דוח יחידות מידה והמרות")],
 "MBEW": [("RMSTKPRV / CKM3", "ניתוח מחיר ושכבות חומר")],
 "MCH1": [("RVBCHE00", "דוח אצוות ותאריכי תפוגה (BBD)")],
 "STKO": [("RCSBOM00", "עיבוד/בדיקת עצי מוצר המוני"), ("RCSBI010", "פיצוץ עץ מוצר רב-רמתי")],
 "STPO": [("RCSBI010", "פיצוץ עץ מוצר רב-רמתי"), ("CS_BT", "דוח Where-Used לרכיב")],
 "PLKO": [("RCEXMASS", "עיבוד מתכונים המוני"), ("RCPRECIPE", "דוח/הערכת מתכונים")],
 "MKAL": [("RCC22300 / RSC22300", "בדיקת עקביות המונית של גרסאות ייצור (Pre-check ל-S/4)")],
 "CRHD": [("CR05 / RCCRSE00", "דוח מרכזי עבודה/משאבים"), ("CM01", "הערכת עומסי קיבולת")],
 "AUFK": [("MD01N (MRP Live)", "הרצת תכנון - פק\"ע מתוכננות"), ("COHV", "עיבוד המוני פק\"ע"), ("CO41/CO48", "המרת פק\"ע מתוכננת")],
 "AFRU": [("CORUPROC / RUDIR", "עיבוד דיווחי ביצוע מ-MES")],
 "JEST": [("RISTAT00", "ניתוח סטטוסים פעילים לאובייקטים"), ("RJEST_DEL", "ארכוב/ניקוי JEST")],
 "TJ02T": [("RISTAT00", "פענוח קודי סטטוס בדוחות")],
 "BUT000": [("MDS_LOAD_COCKPIT", "סנכרון Customer/Vendor Integration ל-BP"), ("RBDMIDOC", "יצירת IDocs להפצה")],
}
def table_funcs(name, theme): return FUNCS.get(name) or STREAM_FUNCS.get(theme, STREAM_FUNCS["master"])
def table_progs(name, theme): return PROGS.get(name) or STREAM_PROGS.get(theme, STREAM_PROGS["master"])
