# -*- coding: utf-8 -*-
"""
Two encyclopedic directories for the SAP PP-PI Migration Blueprint Portal (Project NEO / CBC):
  TCODES_DIR  - Production Transactions & Reports Directory (manufacturing execution).
  TOOLS_DIR   - General Implementer / Basis Toolkit (config, ABAP, Basis, interfaces).
Real SAP expert data; verify version-sensitive Fiori App IDs in the SAP Fiori Apps Reference Library.
"""

# Production Transactions & Reports Directory
# (tcode, scope, hebrew_desc, s4_change, fiori_name, fiori_id, fiori_landscape_he)
TCODES_DIR = [
 ("CS01 / CS02 / CS03", "Both",
  "יצירה / שינוי / תצוגה של עץ מוצר חומר (Material BOM). הליבה להגדרת מבנה הרכיבים של כל מוצר CBC - תרכיז, סוכר, CO2, חומרי אריזה - כולל כמויות, יחידות ופחת רכיב (1%). מקור הפיצוץ לכל פק\"ע.",
  "ללא שינוי מבני; MATNR מורחב ל-40 תווים משפיע על IDNRK והממשקים.",
  "Maintain Bill of Material / Manage Material BOMs", "F1743 / F1813",
  "ב-Fiori פוצל לאפליקציות נפרדות: 'Maintain Bill of Material' (תחזוקה) ו-'Manage Material BOMs' (סקירה וניהול). יש גם Object Page לכל BOM עם היסטוריית שינויים."),
 ("CS11", "Both",
  "פיצוץ עץ מוצר רב-רמתי (Multilevel BOM Explosion) - מציג את כל רמות ההיררכיה של הרכיבים מהמוצר המוגמר ועד חומרי הגלם. כלי ניתוח מרכזי לתכנון חומרים ולבדיקת עלות מוצר ב-CBC.",
  "הפיצוץ עובר ל-HANA-optimized; ב-S/4 התצוגה דרך Fiori עם CDS Views במקום הרצת דוח כבדה.",
  "Display Bill of Material (multilevel)", "(אמת ID)",
  "הפיצוץ הרב-רמתי מוצג כעץ אינטראקטיבי ב-Fiori; ניתן לקפוץ מכל רכיב ל-Object Page שלו (drill-down) במקום מסך SAPGUI סטטי."),
 ("CS12", "Both",
  "פיצוץ עץ מוצר רב-רמתי מלא (כל הרמות בו-זמנית) עם כמויות מצטברות. משמש להפקת רשימת חומרים מלאה (Total BOM) לתמחיר ולרכש מרוכז.",
  "מבוסס HANA; חישוב הכמויות המצטברות מהיר יותר משמעותית.",
  "Display Bill of Material (multilevel)", "(אמת ID)",
  "ב-Fiori הנתונים זמינים גם כ-Analytical tile עם ייצוא ל-Excel/BI לצורך ניתוח עלות חומרים."),
 ("CS13", "Both",
  "פיצוץ עץ מוצר מסוכם (Summarized BOM) - מאחד רכיבים זהים החוזרים במספר רמות לשורה אחת עם כמות כוללת. חיוני לרכש ולתכנון חומר גלם משותף (סוכר/CO2) בין מוצרים.",
  "ללא שינוי לוגי; ביצוע מהיר על HANA.",
  "Display Bill of Material (multilevel)", "(אמת ID)",
  "ב-Fiori הסיכום זמין כ-View אנליטי עם סינון לפי קבוצת חומר."),
 ("CS14", "Both",
  "השוואת עצי מוצר (BOM Comparison) - משווה שני עצי מוצר (או שתי חלופות/גרסאות) ומסמן הבדלים ברכיבים ובכמויות. קריטי לאימות שינויי מתכון מאושרים ב-CBC לפני העברה לייצור.",
  "ללא שינוי; ב-S/4 ניתן להשוות גם דרך Engineering/Change Records.",
  "Compare Bill of Materials", "(אמת ID)",
  "ב-Fiori ההשוואה ויזואלית (side-by-side) עם הדגשת דלתות; משולב בתהליך ניהול שינויים הנדסיים (ECM)."),
 ("CS15", "Both",
  "רשימת 'היכן בשימוש' (Where-Used List) - מציג בכל אילו עצי מוצר/מוצרים משמש רכיב נתון. חיוני לניתוח השפעה (Impact Analysis) בעת החלפת חומר גלם/ספק או ריקול אצווה.",
  "ללא שינוי; ב-S/4 מהיר יותר ומשולב ב-Object Page של החומר.",
  "Where-Used List - Material", "(אמת ID)",
  "ב-Fiori ה-Where-Used נגיש ישירות מ-Object Page של החומר כלשונית, ללא הרצת דוח נפרד."),
 ("CO24", "Both",
  "מידע חוסרים (Missing Parts Info System) - מציג רכיבים חסרים לפק\"ע שלא ניתן לפלוט (מלאי לא מספיק). כלי תפעולי לזיהוי עיכובי ייצור בקו ב-CBC לפני שחרור.",
  "ב-S/4 משולב ב-MRP Live וב-Fiori Material Coverage; בדיקת זמינות בזמן אמת.",
  "Monitor Material Coverage - Net Segments", "F0251",
  "ב-Fiori זה הופך ל-Monitor Material Coverage עם MRP cockpit מבוסס תפקיד; כל חוסר מציג פעולות מוצעות (Solve) ישירות."),
 ("CO46", "Both",
  "דוח התקדמות פק\"ע (Order Progress Report) - מציג את מצב הפק\"ע, הפעולות, הרכיבים והדיווחים במבט אחד. כלי מעקב לתפעול לבקרת קצב ייצור והשלמת אצוות.",
  "מוחלף בדוחות Fiori אנליטיים ולוחות מעקב מבוססי תפקיד.",
  "Production Order/Process Order Progress", "(אמת ID)",
  "ב-Fiori המעקב הופך ל-Overview Page / Analytical tiles עם KPIs (פק\"ע פתוחות, פיגורים) במקום דוח טקסטואלי."),
 ("COOIS", "PP",
  "מערכת מידע פקודות ייצור (Production Order Information System) - דוח מרכזי לסינון, צפייה ועיבוד המוני של פקודות ייצור בדידות (Discrete) לפי סטטוס, חומר, מועד ועוד.",
  "נתמך; אסטרטגית מוחלף ב-Manage Production Orders ובדוחות אנליטיים.",
  "Manage Production Orders", "(אמת ID)",
  "ב-Fiori פוצל ל-List Report עם פילטרים חכמים + Analytical tiles; עיבוד המוני דרך פעולות מרובות-בחירה."),
 ("COOISPI", "PP-PI",
  "מערכת מידע פקודות תהליך (Process Order Information System) - המקבילה של COOIS לפק\"ע תהליכיות (Process Orders). הדוח התפעולי המרכזי של CBC לסינון ועיבוד המוני של פק\"ע ייצור משקאות.",
  "נתמך; מוחלף ב-Manage Process Orders ובלוחות מעקב.",
  "Manage Process Orders", "F4512",
  "ב-Fiori 'Manage Process Orders' (F4512) הוא ה-List Report הראשי; משולב עם Process Order Object Page ועם דיווח (Confirm)."),
 ("COIO", "PP-PI",
  "לוח מעקב פקודות (Order Tracking Cockpit / Process Order Cockpit) - מסך תפעולי מאוחד למעקב אחר פק\"ע התהליך, סטטוסים, חומרים ודיווחים. לב המעקב התפעולי של מנהל הקו ב-CBC.",
  "מוחלף בלוחות Fiori מבוססי תפקיד (Production Operator / Supervisor).",
  "Process Order Cockpit / Operator Dashboard", "(אמת ID)",
  "ב-Fiori המעקב מתפצל לדאשבורדים לפי תפקיד: מפעיל קו (Confirm), מתכנן (Schedule), ומנהל (KPIs) - launchpad מבוסס תפקיד."),
 ("COR1 / COR2 / COR3", "PP-PI",
  "יצירה / שינוי / תצוגה של פקודת ייצור תהליכית (Process Order) - ליבת ביצוע הייצור ב-CBC. שחרור הפק\"ע (REL) מייצר Control Recipe ושולח הוראות תהליך (IDoc LOIPRO) לקו/MES.",
  "מודל מותאם; עלויות ל-ACDOCA; שחרור/Control Recipe נשמרים.",
  "Create / Manage Process Orders", "F4512",
  "ב-Fiori יצירה/שינוי דרך 'Manage Process Orders' + Object Page; פעולות ייעודיות (Release, Confirm, Print) כ-tiles נפרדים."),
 ("CO01 / CO02 / CO03", "PP",
  "יצירה / שינוי / תצוגה של פקודת ייצור בדידה (Discrete Production Order). משמש בייצור בדיד (לא משקאות) - מובא כאן לצורך הבחנה מ-PP-PI; ב-CBC הליבה היא Process Orders.",
  "מודל מותאם; דומה ל-Process Order ב-S/4.",
  "Create / Manage Production Orders", "(אמת ID)",
  "ב-Fiori מקביל ל-Manage Production Orders; בייצור משקאות לא בשימוש (PP-PI מוביל)."),
 ("C201 / C202 / C203", "PP-PI",
  "יצירה / שינוי / תצוגה של מתכון ייצור (Master Recipe) - הגדרת הנוסחה, הפאזות, ההוראות וערכי התקן. כל משקה ב-CBC מיוצר לפי מתכון מאושר; שינוי דורש ניהול שינויים הנדסי (ECM).",
  "ללא שינוי מבני; Fiori 'Manage Master Recipes'.",
  "Manage Master Recipes", "(אמת ID)",
  "ב-Fiori 'Manage Master Recipes' עם Object Page לכל מתכון; שילוב עם Manage Process Instructions ו-PI characteristics."),
 ("CA01 / CA02 / CA03", "PP",
  "יצירה / שינוי / תצוגה של רשימת פעולות (Routing) לייצור בדיד. המקבילה הבדידה של מתכון ה-PP-PI; מובא להבחנה - ב-CBC משתמשים ב-Master Recipe ולא ב-Routing.",
  "ללא שינוי; Fiori 'Manage Routings'.",
  "Manage Routings", "(אמת ID)",
  "ב-Fiori 'Manage Routings'; אינו בשימוש בייצור משקאות תהליכי."),
 ("C223", "PP-PI",
  "ניהול גרסאות ייצור (Production Versions) - מקשר חומר -> עץ מוצר חלופי + מתכון + קו ייצור. ב-S/4HANA חובה מוחלטת לכל ביצוע ייצור; ב-CBC כל שילוב מוצר/קו = גרסה.",
  "גרסת ייצור (VERID) חובה 100% ב-S/4; הרץ בדיקת עקביות לפני ההמרה (RCC22300).",
  "Manage Production Versions", "F2703",
  "ב-Fiori 'Manage Production Versions' (F2703) מרכז את כל הגרסאות עם בדיקת תקינות (consistency) ויזואלית - חיוני ל-Pre-check המיגרציה."),
 ("CO11N", "PP",
  "דיווח ביצוע לפעולה בייצור בדיד (Time Ticket Confirmation). מובא להבחנה; ב-CBC הדיווח התהליכי מתבצע דרך COR6N/CORK והודעות תהליך מהקו.",
  "מוחלף ב-Fiori 'Confirm Production Operation'.",
  "Confirm Production Operation", "F3372",
  "ב-Fiori 'Confirm Production Operation' (F3372) - דיווח מהיר מבוסס תפקיד מפעיל, מותאם למסך מגע בקו."),
 ("COR6N", "PP-PI",
  "דיווח ביצוע לפאזת פק\"ע תהליכית (Process Order Phase Confirmation) - דיווח כמות שיוצרה, פחת וזמני מכונה/אדם לפאזה. מקור הנתונים מהקו (PI Sheet/MES) ובסיס לעלות ולניתוח פחת מול 1% היעד.",
  "ללא שינוי; Fiori Confirmation מבוסס תפקיד.",
  "Confirm Process Order / Operation", "F3372",
  "ב-Fiori הדיווח התהליכי מאוחד עם ה-Confirm app; אוטומציה דרך הודעות תהליך (PPCC1) מ-MES ל-SAP."),
 ("MD04", "Both",
  "רשימת מלאי/דרישות (Stock / Requirements List) - המסך התפעולי המרכזי לתכנון: מציג מלאי, דרישות, פק\"ע, הזמנות רכש וגרעונות לחומר. מנהל החומר ב-CBC עובד מולו יומית.",
  "ב-S/4 נשען על MRP Live; הצגה דרך Fiori Material Coverage עם נתוני זמן אמת מ-HANA.",
  "Monitor Material Coverage - Net Segments", "F0251",
  "ב-Fiori 'Monitor Material Coverage' (F0251) מחליף את MD04 עם MRP cockpit מבוסס תפקיד, אזורי כיסוי (segments) ופעולות פתרון מוצעות."),
 ("MD01 / MD01N", "Both",
  "הרצת תכנון חומרים (MRP / MRP Live). MD01N היא הגרסה החדשה הרצה ישירות על HANA (MRP Live) - מתכננת חומרי גלם, מוצרי ביניים וייצור ומייצרת פק\"ע/הזמנות רכש מתוכננות.",
  "MD01N (MRP Live) מחליף את MD01 הקלאסי; ריצה in-memory מהירה משמעותית, ללא טבלאות ביניים.",
  "Schedule MRP Runs / Monitor Material Requirements", "F2101",
  "ב-Fiori התכנון מנוהל דרך 'Schedule MRP Runs' + 'Monitor Material Coverage'; MRP Live רץ ברקע על HANA והתוצאות נצפות בלוחות מבוססי תפקיד."),
 ("COGI", "Both",
  "עיבוד תנועות מלאי שגויות (Postprocessing of Faulty Goods Movements) - מטפל בפליטות/קליטות אוטומטיות שנכשלו (Backflush). קריטי בייצור משקאות: כשל בפליטת חומר גלם אוטומטית מהקו חייב טיפול מיידי כדי לא לעצור דיווח.",
  "נתמך; ב-S/4 מומלץ לצמצם שגיאות דרך בדיקת זמינות ו-MATDOC.",
  "Manage Material Documents / Clear Faulty Movements", "(אמת ID)",
  "ב-Fiori הטיפול בתנועות שגויות נגיש דרך 'Manage Material Documents' ולוחות חריגים; התראות אוטומטיות על כשלי Backflush."),
 ("CM01 / CM07", "Both",
  "הערכת עומסי קיבולת (Capacity Load / Evaluation) - מציג את העומס מול הזמינות של קווי הייצור/המשאבים. כלי לזיהוי צווארי בקבוק ולתזמון ייצור משקאות יעיל ב-CBC.",
  "ללא שינוי לוגי; ב-S/4 לוח תזמון גרפי (Scheduling Board) מודרני.",
  "Capacity Scheduling Board / Monitor Capacity Utilisation", "(אמת ID)",
  "ב-Fiori 'Capacity Scheduling Board' מספק תזמון גרירה-ושחרור (drag&drop) ויזואלי במקום דוחות הטקסט של CM01/CM07."),
 ("COHV / COHVPI", "Both",
  "עיבוד המוני של פקודות (Mass Processing) - מאפשר שחרור, הדפסה, דיווח או ביטול של מאות פק\"ע בו-זמנית. חיוני לתפעול יומי של עשרות פק\"ע ייצור ב-CBC.",
  "נתמך; משולב עם רקע (Application Jobs) ב-S/4.",
  "Mass Processing - Orders", "(אמת ID)",
  "ב-Fiori העיבוד ההמוני נגיש דרך List Report עם בחירה מרובה + תזמון Application Jobs לרקע."),
 ("CORK / CORT", "PP-PI",
  "השלמה ובקרה של פק\"ע תהליך: CORK = דיווח השלמת פק\"ע; CORT = מוניטור מתכוני בקרה (Control Recipe Monitor). CORT מנהל את שליחת הוראות התהליך לקו/MES ומעקב סטטוס המסירה (Zetes/Daymax).",
  "ללא שינוי; הודעות תהליך נשמרות.",
  "Confirm Process Order / Control Recipe Monitor", "(אמת ID)",
  "ב-Fiori המעקב אחר Control Recipes משולב בלוחות התפעול; סטטוס המסירה ל-MES מוצג כ-KPI."),
 ("CO53", "PP-PI",
  "רשימת עבודה למתכוני בקרה / גיליון PI (Control Recipe / PI Sheet Worklist) - מציג למפעיל הקו את הוראות התהליך לביצוע ולתיעוד (ערכים נמדדים, אישורים). הממשק הישיר בין SAP לאוטומציית הקו ב-CBC.",
  "ב-S/4 מומלץ Manufacturing Execution / Digital Manufacturing במקום PI Sheet קלאסי.",
  "Process Operator Dashboard / Digital Mfg", "(אמת ID)",
  "ב-Fiori גיליון ה-PI הופך לדאשבורד מפעיל מבוסס תפקיד (Process Operator) עם קליטת ערכים ואישורים בזמן אמת מהמסך."),
 ("MB1A / MIGO", "Both",
  "תנועות מלאי: MB1A = פליטת חומר (261) לפק\"ע; MIGO = תנועת מלאי כללית (פליטה/קליטה). פליטת חומרי גלם וקליטת מוצר מוגמר ב-CBC, מסונכרן עם מסופי Zetes.",
  "תנועות מנוהלות ב-MATDOC; MIGO נתמך; Fiori 'Post Goods Movement'.",
  "Post Goods Movement", "(אמת ID)",
  "ב-Fiori 'Post Goods Movement' מאוחד; קליטות/פליטות מהקו מבוצעות גם דרך מסופים ניידים (Zetes) המחוברים ל-OData."),
 ("MB31", "Both",
  "קליטת סחורה לפק\"ע (Goods Receipt for Order, תנועה 101) - קליטת המוצר המוגמר/ביניים שיוצר למלאי, כולל אצווה ותאריך תפוגה. נקודת סיום הייצור והעברה ללוגיסטיקה.",
  "מנוהל ב-MATDOC; נתמך.",
  "Post Goods Receipt for Production", "(אמת ID)",
  "ב-Fiori קליטת המוצר המוגמר דרך 'Post Goods Receipt' או אוטומטית בדיווח הפק\"ע (auto-GR)."),
]

# General Implementer / Basis Toolkit
# (tcode, hebrew_capabilities, s4_impact, fiori_name, fiori_id, fiori_landscape_he)
TOOLS_DIR = [
 ("SPRO", "מרכז ה-Customizing (IMG) - הגדרת כל הקונפיגורציה של SAP: מבנה ארגוני, סוגי פק\"ע, פרופילי סטטוס, פרמטרי MRP, ממשקים ועוד. כלי העבודה המרכזי של המיישם ב-Project NEO.",
  "נשמר ב-S/4 (Customizing עדיין דרך SPRO ב-Backend); חלק מההגדרות נגישות גם דרך 'Manage Your Solution'.",
  "Manage Your Solution / Configure Your Solution", "(אמת ID)",
  "ב-S/4 Cloud הקונפיגורציה עוברת ל-SSCUI (Self-Service Configuration UIs) מבוססי תפקיד; On-Premise עדיין SPRO + SSCUI נבחרים."),
 ("SU01", "תחזוקת משתמשים - יצירה/שינוי/נעילה של משתמשי SAP, הקצאת תפקידים, פרופילים, פרמטרים וסיסמאות. בסיס לאבטחת המערכת ולהרשאות בפרויקט.",
  "נשמר; ב-S/4 ניהול זהויות מומלץ דרך Identity Authentication/Provisioning (IAS/IPS) בענן.",
  "Maintain Business Users / Import Users", "(אמת ID)",
  "ב-Fiori ניהול המשתמשים עובר ל-'Maintain Business Users' ו-launchpad ניהולי; שילוב עם IAS לניהול זהויות מרכזי."),
 ("PFCG", "תחזוקת תפקידים והרשאות (Role Maintenance) - בניית תפקידים (Roles), אובייקטי הרשאה, תפריטים והקצאת אפליקציות. הליבה לאבטחת הגישה לטרנזקציות ולאפליקציות Fiori.",
  "נשמר; ב-S/4 תפקידים כוללים גם קטלוגי Fiori (Catalogs/Groups/Spaces) - 'Business Roles'.",
  "Maintain Business Roles", "F1491",
  "ב-Fiori 'Maintain Business Roles' (F1491) מנהל תפקידים עסקיים הכוללים הרשאות backend + הקצאת אפליקציות/Spaces ל-Launchpad."),
 ("SE37", "Function Builder - יצירה ובדיקה של מודולי פונקציה ו-BAPIs. כלי הליבה של ABAP לבדיקת ממשקים (BAPI_MATERIAL_SAVEDATA, BAPI_PROCORD_CREATE) ולפיתוח אינטגרציות.",
  "נשמר (פיתוח); ב-S/4 מומלץ פיתוח מודרני דרך ADT (Eclipse) ו-RAP.",
  "(Developer tool - אין Fiori ייעודי)", "-",
  "פיתוח ב-S/4 עובר ל-ABAP Development Tools (Eclipse/ADT); SE37 נשאר זמין ב-Backend לבדיקות ולתחזוקה."),
 ("SE38 / SA38", "ABAP Editor (SE38) והרצת דוחות (SA38) - כתיבה, עריכה והרצה של תוכניות ABAP ודוחות סטנדרטיים (RMMG2000, RCC22300). כלי מרכזי לדיווח ולתחזוקה.",
  "נשמר; פיתוח חדש דרך ADT; הרצת דוחות גם דרך Fiori 'Application Jobs'.",
  "(Developer / reporting - אין Fiori ייעודי)", "-",
  "הרצת דוחות ברקע עוברת ל-'Application Jobs' (Fiori); פיתוח קוד ל-ADT. SE38/SA38 נשמרים ב-Backend."),
 ("SE11 / SE16 / SE16N", "מילון הנתונים (Data Dictionary) ועיון בתוכן טבלאות. SE11 = הגדרת טבלאות/Views/Structures; SE16/SE16N = דפדפן תוכן הטבלאות (MARA, MKAL, AFKO). חיוני לבדיקת מבנה ונתונים בפרויקט.",
  "מותאם: ב-S/4 רבות מהטבלאות הקלאסיות הן Compatibility Views; SE16N קורא גם CDS Views. בדוק MATDOC/ACDOCA במקום MSEG/COEP.",
  "View Browser / Custom Fields and Logic", "F2170 / F1433",
  "ב-Fiori 'View Browser' (F2170) לעיון ב-CDS Views; 'Custom Fields and Logic' (F1433) להרחבות שדות. SE16N נשמר ב-Backend ותומך בקריאת CDS."),
 ("SM30 / SM31", "תחזוקת תצוגות טבלה (Table View Maintenance) - עדכון ידני של טבלאות קונפיגורציה (T003O, TCO01, T399X) ללא SPRO. כלי מהיר למיישם לעדכון פרמטרים.",
  "נשמר; שינויי קונפיגורציה נרשמים ל-Transport.",
  "(Config - דרך SSCUI/Manage Your Solution)", "(אמת ID)",
  "חלק מטבלאות הקונפיגורציה נגישות דרך SSCUI ב-Fiori; SM30 נשמר ב-Backend לטבלאות ללא ממשק ייעודי."),
 ("SM37", "מוניטור משימות רקע (Background Job Monitor) - מעקב, תזמון וניתוח של ג'obs ברקע (הרצות MRP, יצירת IDocs, עיבוד המוני). חיוני לתפעול אצוות לילה ב-CBC.",
  "נשמר; ב-S/4 ניהול ותזמון דרך Fiori 'Application Jobs'.",
  "Application Jobs / Job Scheduling Monitor", "F1239",
  "ב-Fiori 'Application Jobs' (F1239) מנהל תזמון, ניטור והתראות על ג'obs מבוסס תפקיד; SM37 נשמר ב-Backend."),
 ("ST22", "ניתוח קריסות ABAP (Dump Analysis) - מציג שגיאות ריצה (Short Dumps) עם stack trace וניתוח שורש. כלי הדיבוג הראשון לכל תקלת תוכנית או ממשק.",
  "נשמר; ב-S/4 משולב גם ב-Fiori monitoring וב-Focused Run.",
  "ABAP Dump Analysis (monitoring)", "(אמת ID)",
  "ב-S/4/Focused Run ניתוח ה-Dumps זמין בלוחות ניטור מרכזיים; ST22 נשמר ב-Backend לניתוח מפורט."),
 ("SM04 / AL08", "מוניטור משתמשים מחוברים (User Monitor) - SM04 = משתמשים בשרת נוכחי; AL08 = כל המשתמשים בכל השרתים. לבקרת עומס, ניתוק תהליכים ופתרון נעילות.",
  "נשמר; ניטור מרכזי דרך Fiori/Focused Run.",
  "(System monitoring - Focused Run)", "(אמת ID)",
  "ב-S/4 ניטור המשתמשים והעומסים עובר ללוחות Fiori מרכזיים (Focused Run / Cloud ALM)."),
 ("WE02 / WE05 / WE19", "מוניטור IDocs - WE02/WE05 = צפייה וניתוח IDocs נכנסים/יוצאים (MATMAS, LOIPRO) וסטטוסים; WE19 = כלי בדיקה (test tool). הליבה לפתרון תקלות בממשקים ל-Zetes ו-Daymax.",
  "נשמר; ב-S/4 ניטור הודעות מומלץ דרך 'Message Monitoring' (AIF/Fiori).",
  "Monitor IDocs / Message Dashboard", "(אמת ID)",
  "ב-Fiori ניטור ה-IDocs/ממשקים עובר ל-'Message Monitoring' ולוחות AIF מבוססי תפקיד עם התראות על כשלים בממשקי הלוגיסטיקה."),
 ("WE20 / WE21", "פרופילי שותפים ויציאות (Partner Profiles & Ports) - WE20 = הגדרת פרופיל שותף (אילו IDocs נשלחים/מתקבלים לכל שותף); WE21 = הגדרת פורטים (tRFC/File). מגדיר את צינור התקשורת ל-Zetes/Daymax.",
  "נשמר; הגדרות הממשק זהות, מומלץ AIF לניטור.",
  "(Interface config - Communication Mgmt)", "(אמת ID)",
  "ב-S/4 Cloud ההגדרות עוברות ל-'Communication Arrangements/Systems'; On-Premise נשמר WE20/WE21 + AIF."),
 ("BD64", "מודל הפצה (Distribution Model / ALE) - הגדרת אילו הודעות (Message Types) מופצות בין מערכות SAP/חיצוניות. בסיס ה-ALE לתשתית ה-IDoc של המפעל.",
  "נשמר; תשתית ALE/IDoc זהה ב-S/4.",
  "(ALE config - Backend)", "-",
  "מודל ההפצה נשמר ב-Backend; ניטור ההפצה משולב ב-Message Monitoring."),
 ("SMQ1 / SMQ2", "מוניטור תורים (qRFC Queues) - SMQ1 = תור יוצא (outbound); SMQ2 = תור נכנס (inbound). מעקב וטיפול בהודעות תקועות בתקשורת אסינכרונית בין SAP למערכות (CIF/MES).",
  "נשמר; ניטור התורים גם דרך Fiori/Focused Run.",
  "Monitor Outbound/Inbound Queues", "(אמת ID)",
  "ב-Fiori ניטור התורים זמין בלוחות מרכזיים; טיפול בהודעות תקועות (requeue/delete) מבוסס תפקיד."),
 ("STMS / SE09 / SE10", "ניהול תעבורה (Transport Management) - STMS = נוף התעבורה והעברת בקשות בין סביבות (DEV->QA->PRD); SE09/SE10 = ארגון בקשות התעבורה. ליבת ה-Change Management של הפרויקט.",
  "נשמר On-Premise; ב-S/4 Cloud דרך 'Manage Software Collection' / Cloud Transport Management (BTP).",
  "Export/Import Software Collection / cTMS", "(אמת ID)",
  "ב-S/4 Cloud התעבורה עוברת ל-Cloud Transport Management (BTP) ולכלי Fiori; On-Premise נשמר STMS."),
 ("ST05 / SAT", "כלי Trace וביצועים - ST05 = SQL/RFC/Buffer trace לניתוח ביצועי שאילתות וממשקים; SAT = ניתוח זמן ריצה (Runtime Analysis). חיוני לאופטימיזציה של דוחות וממשקים כבדים.",
  "נשמר; ב-S/4 דגש על ביצועי HANA - בדוק שאילתות מול CDS/Code Pushdown.",
  "(Performance - Backend/ADT)", "-",
  "ב-S/4 ניתוח הביצועים משולב ב-ADT וב-HANA tooling; ST05/SAT נשמרים ב-Backend לניתוח עמוק."),
 ("SLG1", "יומן יישום (Application Log) - מציג הודעות, אזהרות ושגיאות שתוכניות/ממשקים רשמו (לדוגמה כשלי המרת BP, שגיאות MRP). כלי מעקב מרכזי לאבחון תהליכים ברקע.",
  "נשמר; חלק מהלוגים נגישים גם דרך Fiori 'Application Logs'.",
  "Display Application Logs", "(אמת ID)",
  "ב-Fiori 'Application Logs' מרכז את יומני היישום מבוסס תפקיד עם סינון לפי אובייקט/חומרת הודעה."),
 ("BP", "שותף עסקי (Business Partner) - נקודת הכניסה היחידה לניהול לקוחות/ספקים ב-S/4HANA (מחליף XK01/MK01/XD01). ניהול תפקידים (Roles), קבוצות וכתובות. קריטי לספקי חומרי הגלם של CBC.",
  "מחליף - ב-S/4 BP חובה; נדרש CVI להמרת LFA1/KNA1 ל-BUT000 (SAP Note 2265093).",
  "Manage Business Partner Master Data", "(אמת ID)",
  "ב-Fiori ניהול ה-BP מבוסס תפקיד עם Object Page לכל שותף; תפקידי ספק/לקוח מנוהלים כ-BP Roles באותה רשומה."),
]
